DROP DATABASE IF EXISTS DBHOTEL_s;
CREATE DATABASE DBHOTEL_s;
USE DBHOTEL_s;

----------------------------
-- TABELLA HOTEL
----------------------------
CREATE TABLE HOTEL(
    nome VARCHAR(100) PRIMARY KEY,
    stato VARCHAR(30) NOT NULL,
    citta VARCHAR(30) NOT NULL,
    indirizzo VARCHAR(60) NOT NULL,
    stelle INT NOT NULL
);

CREATE TABLE CAMERA(
    numero VARCHAR(5),
    hotel VARCHAR(100) NOT NULL,
    categoria VARCHAR(30) NOT NULL,
    prezzo INT NOT NULL,
    max_ospiti INT NOT NULL,
    disponibilita ENUM('true', 'false') NOT NULL,
    CONSTRAINT fk_hotel
		FOREIGN KEY(hotel)
        REFERENCES HOTEL(nome)
);

INSERT INTO HOTEL(nome, stato, citta, indirizzo, stelle)
VALUES
('The Ritz-Carlton Atlanta','Stati Uniti','Atlanta','181 Peachtree Street NE',5),
('Atlanta Marriott Marquis','Stati Uniti','Atlanta','265 Peachtree Center Ave',4),
('Hyatt Regency Atlanta','Stati Uniti','Atlanta','265 Peachtree Street NE',4),
('Burj Al Arab Jumeirah','Emirati Arabi Uniti','Dubai','Jumeirah Beach Road',5),
('Atlantis The Palm','Emirati Arabi Uniti','Dubai','Crescent Road Palm Jumeirah',5),
('Rove Downtown Dubai','Emirati Arabi Uniti','Dubai','312 Al Mustaqbal Street',4),
('The Adolphus','Stati Uniti','Dallas','1321 Commerce Street',5),
('Omni Dallas Hotel','Stati Uniti','Dallas','555 South Lamar',4),
('Magnolia Hotel Dallas','Stati Uniti','Dallas','1401 Commerce Street',4),
('The Ritz-Carlton Tokyo','Giappone','Tokyo','Akasaka 9-7-1',5),
('Park Hyatt Tokyo','Giappone','Tokyo','Nishi Shinjuku 3-7-1-2',5),
('Hotel Gracery Shinjuku','Giappone','Tokyo','Kabukicho 1-19-1',4),
('The Savoy','Regno Unito','Londra','Strand',5),
('The Langham London','Regno Unito','Londra','1C Portland Place',5),
('Point A Hotel Westminster','Regno Unito','Londra','118 Westminster Bridge Road',3),
('The Brown Palace','Stati Uniti','Denver','321 17th Street',5),
('Hyatt Regency Denver','Stati Uniti','Denver','650 15th Street',4),
('Hampton Inn Downtown Denver','Stati Uniti','Denver','1845 Sherman Street',3),
('Ciragan Palace Kempinski','Turchia','Istanbul','Ciragan Caddesi 32',5),
('The Marmara Taksim','Turchia','Istanbul','Taksim Meydani',5),
('Hotel Amira Istanbul','Turchia','Istanbul','Kucuk Ayasofya Mahallesi',4),
('The Peninsula Chicago','Stati Uniti','Chicago','108 East Superior Street',5),
('The Langham Chicago','Stati Uniti','Chicago','330 North Wabash Avenue',5),
('Congress Plaza Hotel','Stati Uniti','Chicago','520 South Michigan Avenue',3),
('The Imperial New Delhi','India','Nuova Delhi','Janpath',5),
('Taj Palace New Delhi','India','Nuova Delhi','Sardar Patel Marg',5),
('The Connaught New Delhi','India','Nuova Delhi','Connaught Place',4),
('The Peninsula Shanghai','Cina','Shanghai','32 Zhongshan East 1st Road',5),
('Fairmont Peace Hotel','Cina','Shanghai','20 Nanjing East Road',5),
('Holiday Inn Shanghai Nanjing Road','Cina','Shanghai','595 Jiujiang Road',4),
('The Beverly Hills Hotel','Stati Uniti','Los Angeles','9641 Sunset Boulevard',5),
('InterContinental Los Angeles Downtown','Stati Uniti','Los Angeles','900 Wilshire Boulevard',5),
('Hollywood Hotel','Stati Uniti','Los Angeles','1160 North Vermont Avenue',3),
('Four Seasons Guangzhou','Cina','Guangzhou','Zhujiang West Road',5),
('The Ritz-Carlton Guangzhou','Cina','Guangzhou','Tianhe District',5),
('Guangzhou Marriott Tianhe','Cina','Guangzhou','Tianhe Road',4),
('Signiel Seoul','Corea del Sud','Seoul','300 Olympic-ro',5),
('Four Seasons Hotel Seoul','Corea del Sud','Seoul','97 Saemunan-ro',5),
('LOTTE City Hotel Myeongdong','Corea del Sud','Seoul','362 Samil-daero',4),
('Le Bristol Paris','Francia','Parigi','Rue du Faubourg Saint-Honore 112',5),
('Hotel Lutetia Paris','Francia','Parigi','Boulevard Raspail 45',5),
('Novotel Paris Centre Tour Eiffel','Francia','Parigi','Quai de Grenelle 61',4),
('Marina Bay Sands','Singapore','Singapore','10 Bayfront Avenue',5),
('The Fullerton Hotel Singapore','Singapore','Singapore','1 Fullerton Square',5),
('Hotel Boss','Singapore','Singapore','500 Jalan Sultan',4),
('Waldorf Astoria Beijing','Cina','Pechino','5 Jin Yu Hutong',5),
('Grand Hyatt Beijing','Cina','Pechino','1 East Chang An Avenue',5),
('Novotel Beijing Peace','Cina','Pechino','3 Jinyu Hutong',4),
('Kimpton De Witt Amsterdam','Paesi Bassi','Amsterdam','Nieuwezijds Voorburgwal 5',5),
('Park Plaza Victoria Amsterdam','Paesi Bassi','Amsterdam','Damrak 1-5',4),
('NH Collection Amsterdam Barbizon Palace','Paesi Bassi','Amsterdam','Prins Hendrikkade 59-72',5),
('The Westin Palace Madrid','Spagna','Madrid','Plaza de las Cortes 7',5),
('Mandarin Oriental Ritz Madrid','Spagna','Madrid','Plaza de la Lealtad 5',5),
('Hotel Regina Madrid','Spagna','Madrid','Alcala 19',4),
('The Plaza Hotel','Stati Uniti','New York','768 5th Avenue',5),
('The St. Regis New York','Stati Uniti','New York','2 East 55th Street',5),
('Pod Times Square','Stati Uniti','New York','400 West 42nd Street',3),
('Mandarin Oriental Bangkok','Thailandia','Bangkok','Charoen Krung Road',5),
('Shangri-La Bangkok','Thailandia','Bangkok','89 Soi Wat Suan Plu',5),
('Amara Bangkok Hotel','Thailandia','Bangkok','Surawong Road',4),
('Steigenberger Frankfurter Hof','Germania','Francoforte','Am Kaiserplatz',5),
('JW Marriott Hotel Frankfurt','Germania','Francoforte','Thurn-und-Taxis-Platz 2',5),
('Moxy Frankfurt City Center','Germania','Francoforte','Thurn-und-Taxis-Platz 8',3),
('The Ritz-Carlton Shenzhen','Cina','Shenzhen','116 Fuhua Third Road',5),
('Four Seasons Shenzhen','Cina','Shenzhen','138 Fuhua Third Road',5),
('Hyatt Place Shenzhen Airport','Cina','Shenzhen','Baoan District',4),
('The Ritz-Carlton Charlotte','Stati Uniti','Charlotte','201 East Trade Street',5),
('Grand Bohemian Charlotte','Stati Uniti','Charlotte','201 West Trade Street',4),
('Hilton Charlotte Uptown','Stati Uniti','Charlotte','222 East Third Street',4),
('Bellagio Las Vegas','Stati Uniti','Las Vegas','3600 Las Vegas Boulevard South',5),
('The Venetian Resort','Stati Uniti','Las Vegas','3355 Las Vegas Boulevard South',5),
('Excalibur Hotel & Casino','Stati Uniti','Las Vegas','3850 Las Vegas Boulevard South',4),
('Waldorf Astoria Orlando','Stati Uniti','Orlando','14200 Bonnet Creek Resort Lane',5),
('Hyatt Regency Orlando','Stati Uniti','Orlando','9801 International Drive',4),
('Avanti International Resort','Stati Uniti','Orlando','8738 International Drive',3),
('Mandarin Oriental Kuala Lumpur','Malesia','Kuala Lumpur','Kuala Lumpur City Centre',5),
('Grand Hyatt Kuala Lumpur','Malesia','Kuala Lumpur','Jalan Pinang 12',5),
('Hotel Sentral KL','Malesia','Kuala Lumpur','Jalan Tun Sambanthan 30',3),
('Fontainebleau Miami Beach','Stati Uniti','Miami','4441 Collins Avenue',5),
('EAST Miami','Stati Uniti','Miami','788 Brickell Plaza',5),
('YVE Hotel Miami','Stati Uniti','Miami','146 Biscayne Boulevard',3),
('The Taj Mahal Palace','India','Mumbai','Apollo Bunder',5),
('Trident Nariman Point','India','Mumbai','Nariman Point',5),
('President Mumbai','India','Mumbai','Cuffe Parade',4),
('Majestic Hotel & Spa Barcelona','Spagna','Barcellona','Passeig de Gracia 68',5),
('Hotel Arts Barcelona','Spagna','Barcellona','Marina 19-21',5),
('Catalonia Ramblas','Spagna','Barcellona','Pelai 28',4),
('Niccolo Chengdu','Cina','Chengdu','Tower 3 IFS',5),
('The Ritz-Carlton Chengdu','Cina','Chengdu','269 Shuncheng Avenue',5),
('Holiday Inn Chengdu Century City','Cina','Chengdu','208 East Tower Century City',4),
('The Peninsula Hong Kong','Cina','Hong Kong','Salisbury Road',5),
('Mandarin Oriental Hong Kong','Cina','Hong Kong','Connaught Road Central 5',5),
('B P International','Cina','Hong Kong','Austin Road 8',4),
('Fairmont Olympic Hotel','Stati Uniti','Seattle','411 University Street',5),
('Grand Hyatt Seattle','Stati Uniti','Seattle','721 Pine Street',4),
('The Belltown Inn','Stati Uniti','Seattle','2301 Third Avenue',3),
('Mandarin Oriental Doha','Qatar','Doha','Msheireb Downtown',5),
('JW Marriott Marquis City Center Doha','Qatar','Doha','Conference Centre Street',5),
('Millennium Central Doha','Qatar','Doha','Airport Road',4),
('Arizona Biltmore','Stati Uniti','Phoenix','2400 East Missouri Avenue',5),
('JW Marriott Phoenix Desert Ridge','Stati Uniti','Phoenix','5350 East Marriott Drive',5),
('Hilton Garden Inn Phoenix Airport','Stati Uniti','Phoenix','3422 East Elwood Street',3),
('Fairmont San Francisco','Stati Uniti','San Francisco','950 Mason Street',5),
('InterContinental San Francisco','Stati Uniti','San Francisco','888 Howard Street',4),
('Hotel Stratford','Stati Uniti','San Francisco','242 Powell Street',3),
('The Manila Hotel','Filippine','Manila','One Rizal Park',5),
('New World Makati Hotel','Filippine','Manila','Esperanza Street',5),
('Red Planet Manila Bay','Filippine','Manila','Arquiza Street',3),
('Hotel Eden','Italia','Roma','Via Ludovisi 49',5),
('Anantara Palazzo Naiadi','Italia','Roma','Piazza della Repubblica 48',5),
('UNAHOTELS Decò Roma','Italia','Roma','Via Giovanni Amendola 57',4),
('Grand Hyatt Taipei','Taiwan','Taipei','2 Songshou Road',5),
('Taipei Marriott Hotel','Taiwan','Taipei','199 Lequn 2nd Road',5),
('City Suites Taipei','Taiwan','Taipei','169 Nanjing West Road',4),
('The Ritz-Carlton Jeddah','Arabia Saudita','Jeddah','Al Hamra District',5),
('Rosewood Jeddah','Arabia Saudita','Jeddah','Corniche Road',5),
('Centro Shaheen Jeddah','Arabia Saudita','Jeddah','Prince Sultan Road',4),
('DoubleTree by Hilton Newark Penn Station','Stati Uniti','Newark','Gateway Center',4),
('TRYP by Wyndham Newark Downtown','Stati Uniti','Newark','24 East Park Street',4),
('Courtyard Newark Downtown','Stati Uniti','Newark','858 Broad Street',3),
('Niccolo Chongqing','Cina','Chongqing','Jiangbei District',5),
('Hilton Chongqing','Cina','Chongqing','Zhongshan Third Road',4),
('Glenview ITC Plaza Chongqing','Cina','Chongqing','Minquan Road',5),
('The Post Oak Hotel','Stati Uniti','Houston','1600 West Loop South',5),
('Hilton Americas Houston','Stati Uniti','Houston','1600 Lamar Street',4),
('Club Quarters Houston','Stati Uniti','Houston','1085 Rusk Street',3),
('Four Seasons Hangzhou at West Lake','Cina','Hangzhou','Lingyin Road 5',5),
('Grand Hyatt Hangzhou','Cina','Hangzhou','Hubin Road 28',5),
('Holiday Inn Hangzhou CBD','Cina','Hangzhou','Qianjiang Road 20',4),
('Sofitel Kunming','Cina','Kunming','South Huancheng Road 777',5),
('Crowne Plaza Kunming City Centre','Cina','Kunming','Dongfeng East Road 399',4),
('Fairyland Hotel Kunming','Cina','Kunming','Beijing Road 147',3),
('Novotel Xianyang International Airport','Cina','Xianyang','Airport West Avenue',4),
('Licai Tianxi Hotel','Cina','Xianyang','Weicheng District',4),
('Xianyang Ocean Spring Hotel','Cina','Xianyang','Century Avenue',3),
('Fairmont Royal York','Canada','Toronto','100 Front Street West',5),
('The Ritz-Carlton Toronto','Canada','Toronto','181 Wellington Street West',5),
('Chelsea Hotel Toronto','Canada','Toronto','33 Gerrard Street West',4),
('Grand Hyatt Bogota','Colombia','Bogota','Calle 24A 57-60',5),
('Hilton Bogota','Colombia','Bogota','Carrera 7 No.72-41',5),
('Hotel Estelar La Fontana','Colombia','Bogota','Avenida 127',4),
('Four Seasons Hotel Mexico City','Messico','Città del Messico','Paseo de la Reforma 500',5),
('Hyatt Regency Mexico City','Messico','Città del Messico','Campos Eliseos 204',5),
('Hotel Castropol','Messico','Città del Messico','Avenida Pino Suarez 58',3);

INSERT INTO CAMERA(numero, hotel, categoria, prezzo, max_ospiti, disponibilita)
VALUES
('401', 'The Ritz-Carlton Atlanta', 'Camera Standard', 199, 2, 'false'),
('1005', 'The Ritz-Carlton Atlanta', 'Family Suite', 380, 4, 'true'),
('2001', 'The Ritz-Carlton Atlanta', 'Presidential Suite', 840, 4, 'true'),
('421', 'Atlanta Marriott Marquis', 'Executive Room', 360, 2, 'true'),
('1011', 'Atlanta Marriott Marquis', 'Royal Room', 587, 3, 'true'),
('1301', 'Atlanta Marriott Marquis', 'Royal Suite', 695, 4, 'true'),
('516', 'Hyatt Regency Atlanta', 'Executive King Room', 241, 2, 'false'),
('901', 'Hyatt Regency Atlanta', 'Skyline Corner Suite', 410, 4, 'true'),
('401', 'Burj Al Arab Jumeirah', 'Elite Loft', 1342, 2, 'true'),
('720', 'Burj Al Arab Jumeirah', 'Cityview Room', 863, 2, 'true'),
('851', 'Burj Al Arab Jumeirah', 'Presidential Loft', 1196, 2, 'false'),
('101', 'Atlantis The Palm', 'Ocean Loft', 1456, 2, 'false'),
('401', 'Atlantis The Palm', 'Standard Penthouse', 1776, 4, 'true'),
('540', 'Atlantis The Palm', 'Deluxe Penthouse', 2498, 4, 'true'),
('301', 'Rove Downtown Dubai', 'Executive Room', 212, 2, 'true'),
('101', 'The Adolphus', 'Garden Loft', 305, 3, 'false'),
('401', 'The Adolphus', 'Elite Residence', 483, 2, 'false'),
('101', 'Omni Dallas Hotel', 'Premier Suite', 633, 4, 'false'),
('316', 'Omni Dallas Hotel', 'Executive Residence', 419, 2, 'true'),
('109', 'Magnolia Hotel Dallas', 'City Family Suite', 470, 2, 'false'),
('211', 'Magnolia Hotel Dallas', 'Signature Loft', 587, 3, 'true'),
('301', 'Magnolia Hotel Dallas', 'Signature Junior Suite', 595, 2, 'false'),
('423', 'The Ritz-Carlton Tokyo', 'Garden Penthouse', 467, 2, 'true'),
('601', 'The Ritz-Carlton Tokyo', 'Club Suite', 2442, 2, 'false'),
('611', 'The Ritz-Carlton Tokyo', 'Premier King Room', 1747, 2, 'false'),
('204', 'Park Hyatt Tokyo', 'Signature Suite', 2221, 2, 'true'),
('421', 'Park Hyatt Tokyo', 'Signature Loft', 1264, 3, 'false'),
('501', 'Park Hyatt Tokyo', 'Grand Suite', 2410, 3, 'true'),
('301', 'Hotel Gracery Shinjuku', 'Residence', 201, 2, 'false'),
('413', 'Hotel Gracery Shinjuku', 'Premier Loft', 299, 2, 'true'),
('221', 'The Savoy', 'Royal Suite', 968, 4, 'true'),
('501', 'The Savoy', 'Ocean Studio', 1194, 3, 'true'),
('301', 'The Langham London', 'Executive King Room', 1907, 2, 'true'),
('551', 'The Langham London', 'Royal Corner Suite', 1609, 2, 'true'),
('716', 'The Langham London', 'Grand Queen Room', 1995, 4, 'false'),
('201', 'Point A Hotel Westminster', 'Grand King Room', 85, 2, 'false'),
('307', 'The Brown Palace', 'Panorama Family Suite', 1831, 2, 'true'),
('401', 'The Brown Palace', 'Ocean Family Suite', 2178, 2, 'false'),
('526', 'The Brown Palace', 'Royal Residence', 2307, 2, 'false'),
('220', 'Hyatt Regency Denver', 'Ocean Penthouse', 524, 2, 'false'),
('421', 'Hyatt Regency Denver', 'City Residence', 473, 4, 'false'),
('101', 'Hampton Inn Downtown Denver', 'Executive Corner Suite', 152, 2, 'true'),
('214', 'Ciragan Palace Kempinski', 'Heritage Suite', 1185, 2, 'false'),
('303', 'Ciragan Palace Kempinski', 'Signature King Room', 451, 2, 'false'),
('110', 'The Marmara Taksim', 'Royal Studio', 303, 3, 'false'),
('116', 'The Marmara Taksim', 'Signature King Room', 205, 3, 'true'),
('201', 'Hotel Amira Istanbul', 'Panorama Queen Room', 378, 2, 'true'),
('401', 'Hotel Amira Istanbul', 'City Suite', 141, 2, 'true'),
('317', 'The Peninsula Chicago', 'Grand Suite', 2308, 2, 'false'),
('511', 'The Peninsula Chicago', 'Grand Studio', 1021, 2, 'false'),
('613', 'The Peninsula Chicago', 'Grand Residence', 2476, 2, 'false'),
('501', 'The Langham Chicago', 'Grand Suite', 1170, 2, 'false'),
('207', 'Congress Plaza Hotel', 'Royal Corner Suite', 255, 2, 'true'),
('401', 'The Imperial New Delhi', 'Signature Suite', 191, 2, 'false'),
('618', 'The Imperial New Delhi', 'Garden Junior Suite', 559, 3, 'true'),
('701', 'The Imperial New Delhi', 'Heritage Penthouse', 570, 2, 'true'),
('201', 'Taj Palace New Delhi', 'Elite Queen Room', 830, 3, 'true'),
('415', 'Taj Palace New Delhi', 'Grand Corner Suite', 1147, 4, 'true'),
('121', 'The Connaught New Delhi', 'Heritage Penthouse', 513, 2, 'true'),
('301', 'The Connaught New Delhi', 'Royal Family Suite', 649, 2, 'true'),
('317', 'The Peninsula Shanghai', 'Elite Loft', 2566, 3, 'true'),
('606', 'The Peninsula Shanghai', 'Signature King Room', 832, 3, 'true'),
('212', 'Fairmont Peace Hotel', 'Signature Queen Room', 547, 3, 'false'),
('505', 'Fairmont Peace Hotel', 'Skyline Residence', 597, 2, 'true'),
('801', 'Fairmont Peace Hotel', 'City Residence', 409, 2, 'true'),
('308', 'Holiday Inn Shanghai Nanjing Road', 'Signature Loft', 577, 2, 'false'),
('721', 'The Beverly Hills Hotel', 'Skyline Studio', 445, 2, 'true'),
('312', 'InterContinental Los Angeles Downtown', 'Garden Loft', 572, 2, 'false'),
('605', 'InterContinental Los Angeles Downtown', 'Executive Queen Room', 504, 4, 'true'),
('210', 'Hollywood Hotel', 'Premier Penthouse', 340, 4, 'false'),
('409', 'Hollywood Hotel', 'Garden Family Suite', 458, 4, 'true'),
('111', 'Four Seasons Guangzhou', 'Panorama Queen Room', 1832, 2, 'false'),
('509', 'Four Seasons Guangzhou', 'Elite Studio', 1403, 4, 'true'),
('319', 'The Ritz-Carlton Guangzhou', 'Deluxe Corner Suite', 1326, 2, 'false'),
('602', 'The Ritz-Carlton Guangzhou', 'Grand Family Suite', 2240, 3, 'false'),
('105', 'Guangzhou Marriott Tianhe', 'Executive Studio', 645, 2, 'false'),
('231', 'Signiel Seoul', 'Panorama Junior Suite', 493, 2, 'false'),
('410', 'Signiel Seoul', 'Skyline King Room', 488, 3, 'true'),
('406', 'Four Seasons Hotel Seoul', 'Elite Queen Room', 2657, 2, 'true'),
('141', 'LOTTE City Hotel Myeongdong', 'Heritage Corner Suite', 294, 4, 'true'),
('226', 'LOTTE City Hotel Myeongdong', 'Skyline Corner Suite', 146, 2, 'false'),
('316', 'Le Bristol Paris', 'Garden Studio', 248, 4, 'false'),
('501', 'Le Bristol Paris', 'Skyline Penthouse', 464, 2, 'false'),
('212', 'Hotel Lutetia Paris', 'Deluxe King Room', 144, 2, 'false'),
('146', 'Novotel Paris Centre Tour Eiffel', 'Skyline Family Suite', 426, 4, 'false'),
('301', 'Novotel Paris Centre Tour Eiffel', 'Ocean Queen Room', 156, 2, 'false'),
('401', 'Novotel Paris Centre Tour Eiffel', 'Deluxe Corner Suite', 329, 2, 'true'),
('311', 'Marina Bay Sands', 'Club Residence', 290, 2, 'false'),
('416', 'Marina Bay Sands', 'Heritage Family Suite', 565, 3, 'true'),
('607', 'Marina Bay Sands', 'Deluxe Queen Room', 378, 2, 'false'),
('129', 'The Fullerton Hotel Singapore', 'Elite Studio', 244, 4, 'false'),
('501', 'The Fullerton Hotel Singapore', 'Club Corner Suite', 268, 4, 'true'),
('526', 'The Fullerton Hotel Singapore', 'Ocean King Room', 596, 3, 'false'),
('238', 'Hotel Boss', 'Premier Penthouse', 196, 2, 'false'),
('411', 'Waldorf Astoria Beijing', 'Ocean King Room', 2643, 2, 'false'),
('521', 'Waldorf Astoria Beijing', 'Grand Family Suite', 2022, 2, 'true'),
('256', 'Grand Hyatt Beijing', 'Skyline King Room', 400, 3, 'true'),
('401', 'Grand Hyatt Beijing', 'Garden Queen Room', 596, 3, 'false'),
('503', 'Grand Hyatt Beijing', 'Grand Corner Suite', 331, 2, 'false'),
('601', 'Grand Hyatt Beijing', 'Panorama Corner Suite', 371, 2, 'true'),
('221', 'Novotel Beijing Peace', 'Premier Family Suite', 568, 2, 'true'),
('142', 'Kimpton De Witt Amsterdam', 'City Penthouse', 225, 2, 'false'),
('211', 'Kimpton De Witt Amsterdam', 'Signature Junior Suite', 296, 3, 'false'),
('126', 'Park Plaza Victoria Amsterdam', 'Grand Penthouse', 583, 4, 'false'),
('219', 'NH Collection Amsterdam Barbizon Palace', 'Premier Residence', 2341, 2, 'true'),
('310', 'NH Collection Amsterdam Barbizon Palace', 'Ocean Residence', 2233, 4, 'true'),
('220', 'The Westin Palace Madrid', 'Garden Suite', 584, 4, 'false'),
('301', 'The Westin Palace Madrid', 'City Penthouse', 1321, 2, 'true'),
('415', 'The Westin Palace Madrid', 'Premier King Room', 1851, 2, 'false'),
('116', 'Mandarin Oriental Ritz Madrid', 'City Suite', 1888, 2, 'false'),
('250', 'Mandarin Oriental Ritz Madrid', 'Deluxe Queen Room', 1438, 3, 'false'),
('301', 'Mandarin Oriental Ritz Madrid', 'Executive Residence', 2702, 4, 'false'),
('401', 'Hotel Regina Madrid', 'Garden Loft', 568, 2, 'true'),
('205', 'The Plaza Hotel', 'Premier Queen Room', 396, 2, 'false'),
('608', 'The Plaza Hotel', 'Heritage Family Suite', 495, 2, 'false'),
('720', 'The St. Regis New York', 'Executive Queen Room', 2280, 2, 'false'),
('411', 'Pod Times Square', 'Grand Studio', 471, 2, 'false'),
('410', 'Mandarin Oriental Bangkok', 'Garden Studio', 659, 2, 'true'),
('601', 'Mandarin Oriental Bangkok', 'Elite Suite', 1163, 2, 'false'),
('319', 'Shangri-La Bangkok', 'City Residence', 173, 2, 'true'),
('507', 'Shangri-La Bangkok', 'Club Corner Suite', 634, 2, 'true'),
('219', 'Amara Bangkok Hotel', 'Premier Corner Suite', 608, 2, 'false'),
('410', 'Amara Bangkok Hotel', 'Skyline Loft', 590, 3, 'true'),
('415', 'Steigenberger Frankfurter Hof', 'Deluxe Junior Suite', 245, 2, 'false'),
('757', 'JW Marriott Hotel Frankfurt', 'Deluxe Queen Room', 202, 2, 'true'),
('704', 'JW Marriott Hotel Frankfurt', 'Deluxe Studio', 487, 2, 'true'),
('161', 'Moxy Frankfurt City Center', 'City Residence', 210, 4, 'false'),
('650', 'The Ritz-Carlton Shenzhen', 'Panorama Family Suite', 632, 2, 'false'),
('599', 'The Ritz-Carlton Shenzhen', 'Ocean Penthouse', 974, 2, 'false'),
('394', 'Four Seasons Shenzhen', 'Club Corner Suite', 1814, 2, 'false'),
('168', 'Four Seasons Shenzhen', 'Heritage Studio', 1890, 3, 'false'),
('663', 'Hyatt Place Shenzhen Airport', 'Signature Family Suite', 281, 2, 'false'),
('320', 'Hyatt Place Shenzhen Airport', 'Royal Residence', 595, 2, 'false'),
('666', 'The Ritz-Carlton Charlotte', 'Premier Suite', 662, 4, 'false'),
('506', 'The Ritz-Carlton Charlotte', 'City Residence', 2693, 4, 'true'),
('190', 'Grand Bohemian Charlotte', 'Ocean Suite', 241, 2, 'false'),
('143', 'Grand Bohemian Charlotte', 'Signature Junior Suite', 299, 4, 'false'),
('234', 'Grand Bohemian Charlotte', 'City Corner Suite', 475, 2, 'true'),
('308', 'Hilton Charlotte Uptown', 'Ocean Family Suite', 318, 2, 'false'),
('913', 'Bellagio Las Vegas', 'City Queen Room', 581, 3, 'false'),
('332', 'Bellagio Las Vegas', 'Garden Residence', 411, 2, 'true'),
('755', 'The Venetian Resort', 'Signature Residence', 545, 4, 'true'),
('582', 'The Venetian Resort', 'Garden Family Suite', 354, 3, 'true'),
('166', 'The Venetian Resort', 'Heritage Loft', 502, 2, 'true'),
('617', 'Excalibur Hotel & Casino', 'Grand Queen Room', 262, 4, 'false'),
('518', 'Waldorf Astoria Orlando', 'Ocean Studio', 1964, 3, 'true'),
('160', 'Waldorf Astoria Orlando', 'Panorama Suite', 2697, 3, 'false'),
('673', 'Hyatt Regency Orlando', 'Club Studio', 473, 2, 'true'),
('218', 'Avanti International Resort', 'Elite Suite', 394, 2, 'false'),
('462', 'Mandarin Oriental Kuala Lumpur', 'Panorama Family Suite', 2316, 2, 'false'),
('675', 'Mandarin Oriental Kuala Lumpur', 'Panorama Suite', 2528, 2, 'false'),
('105', 'Grand Hyatt Kuala Lumpur', 'Elite Queen Room', 261, 2, 'true'),
('518', 'Grand Hyatt Kuala Lumpur', 'Heritage Queen Room', 632, 4, 'true'),
('985', 'Hotel Sentral KL', 'Panorama Corner Suite', 270, 2, 'true'),
('942', 'Fontainebleau Miami Beach', 'Signature Suite', 609, 2, 'true'),
('724', 'Fontainebleau Miami Beach', 'Heritage Studio', 217, 2, 'true'),
('857', 'EAST Miami', 'Premier Junior Suite', 641, 3, 'true'),
('792', 'EAST Miami', 'City Penthouse', 311, 2, 'true'),
('626', 'EAST Miami', 'Ocean Loft', 284, 3, 'false'),
('423', 'YVE Hotel Miami', 'Signature Loft', 152, 2, 'false'),
('354', 'YVE Hotel Miami', 'Panorama Residence', 97, 4, 'false'),
('760', 'The Taj Mahal Palace', 'Deluxe Penthouse', 1140, 2, 'true'),
('151', 'The Taj Mahal Palace', 'Club Family Suite', 996, 2, 'false'),
('356', 'Trident Nariman Point', 'Panorama Residence', 159, 2, 'true'),
('895', 'Trident Nariman Point', 'Premier Queen Room', 393, 4, 'true'),
('730', 'President Mumbai', 'Premier Studio', 392, 2, 'true'),
('515', 'President Mumbai', 'Skyline Studio', 641, 2, 'true'),
('735', 'Majestic Hotel & Spa Barcelona', 'Signature Junior Suite', 366, 4, 'true'),
('557', 'Majestic Hotel & Spa Barcelona', 'Ocean Loft', 341, 4, 'false'),
('924', 'Majestic Hotel & Spa Barcelona', 'Premier Corner Suite', 598, 4, 'false'),
('880', 'Hotel Arts Barcelona', 'Signature Loft', 183, 4, 'false'),
('886', 'Hotel Arts Barcelona', 'Panorama Queen Room', 472, 2, 'true'),
('347', 'Catalonia Ramblas', 'Skyline Suite', 225, 2, 'true'),
('332', 'Catalonia Ramblas', 'Garden King Room', 173, 2, 'false'),
('874', 'Niccolo Chengdu', 'Premier Residence', 549, 3, 'true'),
('455', 'Niccolo Chengdu', 'Elite Corner Suite', 299, 3, 'true'),
('209', 'The Ritz-Carlton Chengdu', 'Deluxe King Room', 2458, 2, 'false'),
('539', 'The Ritz-Carlton Chengdu', 'Executive Junior Suite', 2610, 2, 'false'),
('803', 'Holiday Inn Chengdu Century City', 'Grand Penthouse', 168, 2, 'false'),
('363', 'The Peninsula Hong Kong', 'Deluxe Loft', 2147, 2, 'true'),
('347', 'The Peninsula Hong Kong', 'Premier Residence', 2401, 2, 'true'),
('984', 'Mandarin Oriental Hong Kong', 'Panorama Junior Suite', 2743, 3, 'false'),
('420', 'Mandarin Oriental Hong Kong', 'Panorama Junior Suite', 2681, 2, 'true'),
('748', 'B P International', 'Royal Suite', 278, 2, 'false'),
('813', 'B P International', 'Ocean Family Suite', 493, 4, 'false'),
('175', 'Fairmont Olympic Hotel', 'City Studio', 517, 2, 'false'),
('175', 'Grand Hyatt Seattle', 'Premier Residence', 203, 2, 'false'),
('960', 'Grand Hyatt Seattle', 'City Queen Room', 161, 2, 'true'),
('991', 'Grand Hyatt Seattle', 'City Family Suite', 203, 3, 'false'),
('337', 'The Belltown Inn', 'Grand Loft', 535, 2, 'true'),
('881', 'Mandarin Oriental Doha', 'Ocean Family Suite', 873, 2, 'true'),
('521', 'Mandarin Oriental Doha', 'City Family Suite', 1193, 2, 'false'),
('774', 'Mandarin Oriental Doha', 'Panorama Residence', 2215, 4, 'true'),
('329', 'JW Marriott Marquis City Center Doha', 'Signature Corner Suite', 384, 2, 'true'),
('785', 'JW Marriott Marquis City Center Doha', 'Club Junior Suite', 296, 2, 'true'),
('638', 'JW Marriott Marquis City Center Doha', 'Panorama King Room', 152, 2, 'false'),
('363', 'Millennium Central Doha', 'City Loft', 386, 2, 'false'),
('709', 'Millennium Central Doha', 'Elite Junior Suite', 340, 2, 'false'),
('517', 'Arizona Biltmore', 'Skyline Junior Suite', 433, 4, 'false'),
('903', 'JW Marriott Phoenix Desert Ridge', 'Deluxe Junior Suite', 398, 2, 'true'),
('992', 'JW Marriott Phoenix Desert Ridge', 'Skyline Queen Room', 366, 4, 'true'),
('239', 'Hilton Garden Inn Phoenix Airport', 'Deluxe Suite', 551, 2, 'false'),
('357', 'Fairmont San Francisco', 'Panorama Family Suite', 311, 2, 'false'),
('366', 'Fairmont San Francisco', 'Deluxe Residence', 549, 2, 'true'),
('644', 'InterContinental San Francisco', 'City Loft', 371, 2, 'false'),
('803', 'InterContinental San Francisco', 'Heritage Junior Suite', 579, 2, 'true'),
('875', 'Hotel Stratford', 'Signature Loft', 336, 4, 'false'),
('931', 'Hotel Stratford', 'Panorama Loft', 602, 2, 'false'),
('160', 'The Manila Hotel', 'Heritage Residence', 490, 2, 'true'),
('511', 'The Manila Hotel', 'Grand Queen Room', 591, 2, 'true'),
('533', 'New World Makati Hotel', 'Heritage Studio', 531, 4, 'true'),
('562', 'New World Makati Hotel', 'Executive Family Suite', 443, 4, 'true'),
('307', 'Red Planet Manila Bay', 'Royal Suite', 105, 2, 'true'),
('526', 'Hotel Eden', 'Skyline King Room', 288, 3, 'false'),
('743', 'Hotel Eden', 'Ocean Junior Suite', 200, 4, 'true'),
('797', 'Hotel Eden', 'Deluxe King Room', 359, 4, 'true'),
('388', 'Anantara Palazzo Naiadi', 'Elite Loft', 450, 2, 'false'),
('674', 'Anantara Palazzo Naiadi', 'Grand Family Suite', 490, 4, 'false'),
('806', 'UNAHOTELS Decò Roma', 'Garden King Room', 547, 3, 'true'),
('354', 'UNAHOTELS Decò Roma', 'Garden King Room', 472, 2, 'true'),
('520', 'Grand Hyatt Taipei', 'City Queen Room', 392, 2, 'true'),
('659', 'Grand Hyatt Taipei', 'Garden King Room', 441, 4, 'false'),
('124', 'Taipei Marriott Hotel', 'Club Residence', 304, 4, 'false'),
('467', 'Taipei Marriott Hotel', 'Club Queen Room', 203, 2, 'false'),
('333', 'City Suites Taipei', 'Signature Loft', 174, 3, 'true'),
('346', 'The Ritz-Carlton Jeddah', 'Skyline Family Suite', 2211, 3, 'false'),
('496', 'The Ritz-Carlton Jeddah', 'Club Penthouse', 529, 4, 'false'),
('885', 'Rosewood Jeddah', 'Ocean Suite', 584, 2, 'false'),
('687', 'Rosewood Jeddah', 'Club King Room', 258, 2, 'false'),
('367', 'Rosewood Jeddah', 'Ocean Loft', 589, 2, 'false'),
('240', 'Centro Shaheen Jeddah', 'Signature Studio', 463, 2, 'true'),
('580', 'Centro Shaheen Jeddah', 'Garden Studio', 146, 3, 'false'),
('704', 'DoubleTree by Hilton Newark Penn Station', 'Deluxe Studio', 190, 2, 'false'),
('418', 'TRYP by Wyndham Newark Downtown', 'Ocean Corner Suite', 153, 2, 'true'),
('210', 'Courtyard Newark Downtown', 'Executive Studio', 645, 3, 'true'),
('492', 'Niccolo Chongqing', 'City Family Suite', 547, 2, 'true'),
('790', 'Niccolo Chongqing', 'Grand Suite', 605, 2, 'true'),
('595', 'Niccolo Chongqing', 'Panorama King Room', 510, 2, 'false'),
('357', 'Hilton Chongqing', 'Grand Suite', 540, 2, 'true'),
('342', 'Hilton Chongqing', 'Skyline Studio', 455, 2, 'true'),
('169', 'Glenview ITC Plaza Chongqing', 'City Penthouse', 288, 2, 'false'),
('608', 'Glenview ITC Plaza Chongqing', 'Royal Corner Suite', 425, 2, 'false'),
('879', 'The Post Oak Hotel', 'Deluxe Queen Room', 266, 4, 'true'),
('647', 'The Post Oak Hotel', 'Royal Residence', 469, 2, 'false'),
('347', 'Hilton Americas Houston', 'Ocean Queen Room', 520, 2, 'false'),
('666', 'Hilton Americas Houston', 'Elite Family Suite', 417, 2, 'false'),
('712', 'Club Quarters Houston', 'Executive Penthouse', 507, 3, 'true'),
('596', 'Club Quarters Houston', 'Garden Residence', 628, 2, 'false'),
('866', 'Four Seasons Hangzhou at West Lake', 'Heritage Junior Suite', 1668, 2, 'false'),
('484', 'Four Seasons Hangzhou at West Lake', 'City Suite', 2040, 3, 'false'),
('576', 'Four Seasons Hangzhou at West Lake', 'Royal King Room', 534, 2, 'false'),
('565', 'Grand Hyatt Hangzhou', 'Royal Corner Suite', 223, 2, 'false'),
('655', 'Grand Hyatt Hangzhou', 'Garden Junior Suite', 562, 3, 'false'),
('180', 'Holiday Inn Hangzhou CBD', 'Panorama Penthouse', 583, 4, 'true'),
('454', 'Sofitel Kunming', 'Club Loft', 548, 3, 'true'),
('921', 'Crowne Plaza Kunming City Centre', 'Royal Corner Suite', 472, 2, 'false'),
('554', 'Crowne Plaza Kunming City Centre', 'Grand Loft', 626, 4, 'true'),
('310', 'Fairyland Hotel Kunming', 'Heritage King Room', 623, 2, 'false'),
('268', 'Novotel Xianyang International Airport', 'Ocean Family Suite', 338, 2, 'true'),
('341', 'Licai Tianxi Hotel', 'Elite King Room', 353, 3, 'true'),
('172', 'Xianyang Ocean Spring Hotel', 'Royal Loft', 388, 2, 'false'),
('984', 'Fairmont Royal York', 'Heritage Loft', 236, 3, 'false'),
('392', 'Fairmont Royal York', 'Grand Penthouse', 142, 2, 'false'),
('103', 'The Ritz-Carlton Toronto', 'Club Loft', 1316, 2, 'false'),
('492', 'The Ritz-Carlton Toronto', 'Deluxe Loft', 2528, 2, 'false'),
('924', 'Chelsea Hotel Toronto', 'Garden Residence', 246, 2, 'true'),
('713', 'Chelsea Hotel Toronto', 'Premier Family Suite', 370, 4, 'true'),
('572', 'Grand Hyatt Bogota', 'City Suite', 311, 2, 'false'),
('209', 'Grand Hyatt Bogota', 'Panorama Queen Room', 467, 2, 'false'),
('234', 'Grand Hyatt Bogota', 'Panorama Penthouse', 404, 3, 'true'),
('626', 'Hilton Bogota', 'Premier Penthouse', 479, 4, 'false'),
('525', 'Hotel Estelar La Fontana', 'Skyline Penthouse', 601, 2, 'false'),
('969', 'Four Seasons Hotel Mexico City', 'Deluxe Junior Suite', 2272, 3, 'true'),
('121', 'Four Seasons Hotel Mexico City', 'Premier Family Suite', 460, 2, 'false'),
('966', 'Hyatt Regency Mexico City', 'Panorama Loft', 582, 3, 'false'),
('512', 'Hyatt Regency Mexico City', 'Panorama Queen Room', 530, 2, 'false'),
('912', 'Hotel Castropol', 'City Penthouse', 554, 2, 'false');
