DROP DATABASE IF EXISTS DBHOTEL;
CREATE DATABASE DBHOTEL;
USE DBHOTEL;

----------------------------
-- TABELLA HOTEL
----------------------------
CREATE TABLE HOTEL(
    nome VARCHAR(100) PRIMARY KEY,
    stato VARCHAR(30) NOT NULL,
    citta VARCHAR(30) NOT NULL,
    indirizzo VARCHAR(60) NOT NULL,
    stelle INT NOT NULL
);

CREATE TABLE CAMERA(
    numero VARCHAR(5),
    hotel VARCHAR(100) NOT NULL,
    categoria VARCHAR(30) NOT NULL,
    prezzo INT NOT NULL,
    max_ospiti INT NOT NULL,
    disponibilita ENUM('true', 'false') NOT NULL,
    CONSTRAINT fk_hotel
		FOREIGN KEY(hotel)
        REFERENCES HOTEL(nome)
);

INSERT INTO HOTEL(nome, stato, citta, indirizzo, stelle)
VALUES
('The Ritz-Carlton Atlanta','Stati Uniti','Atlanta','181 Peachtree Street NE',5),
('Atlanta Marriott Marquis','Stati Uniti','Atlanta','265 Peachtree Center Ave',4),
('Hyatt Regency Atlanta','Stati Uniti','Atlanta','265 Peachtree Street NE',4),
('Burj Al Arab Jumeirah','Emirati Arabi Uniti','Dubai','Jumeirah Beach Road',5),
('Atlantis The Palm','Emirati Arabi Uniti','Dubai','Crescent Road Palm Jumeirah',5),
('Rove Downtown Dubai','Emirati Arabi Uniti','Dubai','312 Al Mustaqbal Street',4),
('The Adolphus','Stati Uniti','Dallas','1321 Commerce Street',5),
('Omni Dallas Hotel','Stati Uniti','Dallas','555 South Lamar',4),
('Magnolia Hotel Dallas','Stati Uniti','Dallas','1401 Commerce Street',4),
('The Ritz-Carlton Tokyo','Giappone','Tokyo','Akasaka 9-7-1',5),
('Park Hyatt Tokyo','Giappone','Tokyo','Nishi Shinjuku 3-7-1-2',5),
('Hotel Gracery Shinjuku','Giappone','Tokyo','Kabukicho 1-19-1',4),
('The Savoy','Regno Unito','Londra','Strand',5),
('The Langham London','Regno Unito','Londra','1C Portland Place',5),
('Point A Hotel Westminster','Regno Unito','Londra','118 Westminster Bridge Road',3),
('The Brown Palace','Stati Uniti','Denver','321 17th Street',5),
('Hyatt Regency Denver','Stati Uniti','Denver','650 15th Street',4),
('Hampton Inn Downtown Denver','Stati Uniti','Denver','1845 Sherman Street',3),
('Ciragan Palace Kempinski','Turchia','Istanbul','Ciragan Caddesi 32',5),
('The Marmara Taksim','Turchia','Istanbul','Taksim Meydani',5),
('Hotel Amira Istanbul','Turchia','Istanbul','Kucuk Ayasofya Mahallesi',4),
('The Peninsula Chicago','Stati Uniti','Chicago','108 East Superior Street',5),
('The Langham Chicago','Stati Uniti','Chicago','330 North Wabash Avenue',5),
('Congress Plaza Hotel','Stati Uniti','Chicago','520 South Michigan Avenue',3),
('The Imperial New Delhi','India','Nuova Delhi','Janpath',5),
('Taj Palace New Delhi','India','Nuova Delhi','Sardar Patel Marg',5),
('The Connaught New Delhi','India','Nuova Delhi','Connaught Place',4),
('The Peninsula Shanghai','Cina','Shanghai','32 Zhongshan East 1st Road',5),
('Fairmont Peace Hotel','Cina','Shanghai','20 Nanjing East Road',5),
('Holiday Inn Shanghai Nanjing Road','Cina','Shanghai','595 Jiujiang Road',4),
('The Beverly Hills Hotel','Stati Uniti','Los Angeles','9641 Sunset Boulevard',5),
('InterContinental Los Angeles Downtown','Stati Uniti','Los Angeles','900 Wilshire Boulevard',5),
('Hollywood Hotel','Stati Uniti','Los Angeles','1160 North Vermont Avenue',3),
('Four Seasons Guangzhou','Cina','Guangzhou','Zhujiang West Road',5),
('The Ritz-Carlton Guangzhou','Cina','Guangzhou','Tianhe District',5),
('Guangzhou Marriott Tianhe','Cina','Guangzhou','Tianhe Road',4),
('Signiel Seoul','Corea del Sud','Seoul','300 Olympic-ro',5),
('Four Seasons Hotel Seoul','Corea del Sud','Seoul','97 Saemunan-ro',5),
('LOTTE City Hotel Myeongdong','Corea del Sud','Seoul','362 Samil-daero',4),
('Le Bristol Paris','Francia','Parigi','Rue du Faubourg Saint-Honore 112',5),
('Hotel Lutetia Paris','Francia','Parigi','Boulevard Raspail 45',5),
('Novotel Paris Centre Tour Eiffel','Francia','Parigi','Quai de Grenelle 61',4),
('Marina Bay Sands','Singapore','Singapore','10 Bayfront Avenue',5),
('The Fullerton Hotel Singapore','Singapore','Singapore','1 Fullerton Square',5),
('Hotel Boss','Singapore','Singapore','500 Jalan Sultan',4),
('Waldorf Astoria Beijing','Cina','Pechino','5 Jin Yu Hutong',5),
('Grand Hyatt Beijing','Cina','Pechino','1 East Chang An Avenue',5),
('Novotel Beijing Peace','Cina','Pechino','3 Jinyu Hutong',4),
('Kimpton De Witt Amsterdam','Paesi Bassi','Amsterdam','Nieuwezijds Voorburgwal 5',5),
('Park Plaza Victoria Amsterdam','Paesi Bassi','Amsterdam','Damrak 1-5',4),
('NH Collection Amsterdam Barbizon Palace','Paesi Bassi','Amsterdam','Prins Hendrikkade 59-72',5),
('The Westin Palace Madrid','Spagna','Madrid','Plaza de las Cortes 7',5),
('Mandarin Oriental Ritz Madrid','Spagna','Madrid','Plaza de la Lealtad 5',5),
('Hotel Regina Madrid','Spagna','Madrid','Alcala 19',4),
('The Plaza Hotel','Stati Uniti','New York','768 5th Avenue',5),
('The St. Regis New York','Stati Uniti','New York','2 East 55th Street',5),
('Pod Times Square','Stati Uniti','New York','400 West 42nd Street',3),
('Mandarin Oriental Bangkok','Thailandia','Bangkok','Charoen Krung Road',5),
('Shangri-La Bangkok','Thailandia','Bangkok','89 Soi Wat Suan Plu',5),
('Amara Bangkok Hotel','Thailandia','Bangkok','Surawong Road',4),
('Steigenberger Frankfurter Hof','Germania','Francoforte','Am Kaiserplatz',5),
('JW Marriott Hotel Frankfurt','Germania','Francoforte','Thurn-und-Taxis-Platz 2',5),
('Moxy Frankfurt City Center','Germania','Francoforte','Thurn-und-Taxis-Platz 8',3),
('The Ritz-Carlton Shenzhen','Cina','Shenzhen','116 Fuhua Third Road',5),
('Four Seasons Shenzhen','Cina','Shenzhen','138 Fuhua Third Road',5),
('Hyatt Place Shenzhen Airport','Cina','Shenzhen','Baoan District',4),
('The Ritz-Carlton Charlotte','Stati Uniti','Charlotte','201 East Trade Street',5),
('Grand Bohemian Charlotte','Stati Uniti','Charlotte','201 West Trade Street',4),
('Hilton Charlotte Uptown','Stati Uniti','Charlotte','222 East Third Street',4),
('Bellagio Las Vegas','Stati Uniti','Las Vegas','3600 Las Vegas Boulevard South',5),
('The Venetian Resort','Stati Uniti','Las Vegas','3355 Las Vegas Boulevard South',5),
('Excalibur Hotel & Casino','Stati Uniti','Las Vegas','3850 Las Vegas Boulevard South',4),
('Waldorf Astoria Orlando','Stati Uniti','Orlando','14200 Bonnet Creek Resort Lane',5),
('Hyatt Regency Orlando','Stati Uniti','Orlando','9801 International Drive',4),
('Avanti International Resort','Stati Uniti','Orlando','8738 International Drive',3),
('Mandarin Oriental Kuala Lumpur','Malesia','Kuala Lumpur','Kuala Lumpur City Centre',5),
('Grand Hyatt Kuala Lumpur','Malesia','Kuala Lumpur','Jalan Pinang 12',5),
('Hotel Sentral KL','Malesia','Kuala Lumpur','Jalan Tun Sambanthan 30',3),
('Fontainebleau Miami Beach','Stati Uniti','Miami','4441 Collins Avenue',5),
('EAST Miami','Stati Uniti','Miami','788 Brickell Plaza',5),
('YVE Hotel Miami','Stati Uniti','Miami','146 Biscayne Boulevard',3),
('The Taj Mahal Palace','India','Mumbai','Apollo Bunder',5),
('Trident Nariman Point','India','Mumbai','Nariman Point',5),
('President Mumbai','India','Mumbai','Cuffe Parade',4),
('Majestic Hotel & Spa Barcelona','Spagna','Barcellona','Passeig de Gracia 68',5),
('Hotel Arts Barcelona','Spagna','Barcellona','Marina 19-21',5),
('Catalonia Ramblas','Spagna','Barcellona','Pelai 28',4),
('Niccolo Chengdu','Cina','Chengdu','Tower 3 IFS',5),
('The Ritz-Carlton Chengdu','Cina','Chengdu','269 Shuncheng Avenue',5),
('Holiday Inn Chengdu Century City','Cina','Chengdu','208 East Tower Century City',4),
('The Peninsula Hong Kong','Cina','Hong Kong','Salisbury Road',5),
('Mandarin Oriental Hong Kong','Cina','Hong Kong','Connaught Road Central 5',5),
('B P International','Cina','Hong Kong','Austin Road 8',4),
('Fairmont Olympic Hotel','Stati Uniti','Seattle','411 University Street',5),
('Grand Hyatt Seattle','Stati Uniti','Seattle','721 Pine Street',4),
('The Belltown Inn','Stati Uniti','Seattle','2301 Third Avenue',3),
('Mandarin Oriental Doha','Qatar','Doha','Msheireb Downtown',5),
('JW Marriott Marquis City Center Doha','Qatar','Doha','Conference Centre Street',5),
('Millennium Central Doha','Qatar','Doha','Airport Road',4),
('Arizona Biltmore','Stati Uniti','Phoenix','2400 East Missouri Avenue',5),
('JW Marriott Phoenix Desert Ridge','Stati Uniti','Phoenix','5350 East Marriott Drive',5),
('Hilton Garden Inn Phoenix Airport','Stati Uniti','Phoenix','3422 East Elwood Street',3),
('Fairmont San Francisco','Stati Uniti','San Francisco','950 Mason Street',5),
('InterContinental San Francisco','Stati Uniti','San Francisco','888 Howard Street',4),
('Hotel Stratford','Stati Uniti','San Francisco','242 Powell Street',3),
('The Manila Hotel','Filippine','Manila','One Rizal Park',5),
('New World Makati Hotel','Filippine','Manila','Esperanza Street',5),
('Red Planet Manila Bay','Filippine','Manila','Arquiza Street',3),
('Hotel Eden','Italia','Roma','Via Ludovisi 49',5),
('Anantara Palazzo Naiadi','Italia','Roma','Piazza della Repubblica 48',5),
('UNAHOTELS Decò Roma','Italia','Roma','Via Giovanni Amendola 57',4),
('Grand Hyatt Taipei','Taiwan','Taipei','2 Songshou Road',5),
('Taipei Marriott Hotel','Taiwan','Taipei','199 Lequn 2nd Road',5),
('City Suites Taipei','Taiwan','Taipei','169 Nanjing West Road',4),
('The Ritz-Carlton Jeddah','Arabia Saudita','Jeddah','Al Hamra District',5),
('Rosewood Jeddah','Arabia Saudita','Jeddah','Corniche Road',5),
('Centro Shaheen Jeddah','Arabia Saudita','Jeddah','Prince Sultan Road',4),
('DoubleTree by Hilton Newark Penn Station','Stati Uniti','Newark','Gateway Center',4),
('TRYP by Wyndham Newark Downtown','Stati Uniti','Newark','24 East Park Street',4),
('Courtyard Newark Downtown','Stati Uniti','Newark','858 Broad Street',3),
('Niccolo Chongqing','Cina','Chongqing','Jiangbei District',5),
('Hilton Chongqing','Cina','Chongqing','Zhongshan Third Road',4),
('Glenview ITC Plaza Chongqing','Cina','Chongqing','Minquan Road',5),
('The Post Oak Hotel','Stati Uniti','Houston','1600 West Loop South',5),
('Hilton Americas Houston','Stati Uniti','Houston','1600 Lamar Street',4),
('Club Quarters Houston','Stati Uniti','Houston','1085 Rusk Street',3),
('Four Seasons Hangzhou at West Lake','Cina','Hangzhou','Lingyin Road 5',5),
('Grand Hyatt Hangzhou','Cina','Hangzhou','Hubin Road 28',5),
('Holiday Inn Hangzhou CBD','Cina','Hangzhou','Qianjiang Road 20',4),
('Sofitel Kunming','Cina','Kunming','South Huancheng Road 777',5),
('Crowne Plaza Kunming City Centre','Cina','Kunming','Dongfeng East Road 399',4),
('Fairyland Hotel Kunming','Cina','Kunming','Beijing Road 147',3),
('Novotel Xianyang International Airport','Cina','Xianyang','Airport West Avenue',4),
('Licai Tianxi Hotel','Cina','Xianyang','Weicheng District',4),
('Xianyang Ocean Spring Hotel','Cina','Xianyang','Century Avenue',3),
('Fairmont Royal York','Canada','Toronto','100 Front Street West',5),
('The Ritz-Carlton Toronto','Canada','Toronto','181 Wellington Street West',5),
('Chelsea Hotel Toronto','Canada','Toronto','33 Gerrard Street West',4),
('Grand Hyatt Bogota','Colombia','Bogota','Calle 24A 57-60',5),
('Hilton Bogota','Colombia','Bogota','Carrera 7 No.72-41',5),
('Hotel Estelar La Fontana','Colombia','Bogota','Avenida 127',4),
('Four Seasons Hotel Mexico City','Messico','Città del Messico','Paseo de la Reforma 500',5),
('Hyatt Regency Mexico City','Messico','Città del Messico','Campos Eliseos 204',5),
('Hotel Castropol','Messico','Città del Messico','Avenida Pino Suarez 58',3),
('Boston Harbor Hotel','Stati Uniti','Boston','70 Rowes Wharf',5),
('The Langham Boston','Stati Uniti','Boston','250 Franklin Street',5),
('Club Quarters Hotel Boston','Stati Uniti','Boston','161 Devonshire Street',4),
('Hotel Fasano São Paulo','Brasile','San Paolo','Rua Vittorio Fasano 88',5),
('Renaissance São Paulo Hotel','Brasile','San Paolo','Alameda Santos 2233',5),
('Ibis Paulista','Brasile','San Paolo','Avenida Paulista 2355',3),
('The Ritz-Carlton Moscow','Russia','Mosca','Tverskaya Street 3',5),
('Metropol Moscow','Russia','Mosca','Teatralny Proezd 2',5),
('Holiday Inn Moscow Sokolniki','Russia','Mosca','Rusakovskaya Street 24',4),
('The Leela Palace Bengaluru','India','Bangaluru','Old Airport Road',5),
('ITC Gardenia Bengaluru','India','Bangaluru','Residency Road',5),
('The Chancery Pavilion','India','Bangaluru','Residency Road',4),
('Hotel Bayerischer Hof','Germania','Monaco','Promenadeplatz 2-6',5),
('Mandarin Oriental Munich','Germania','Monaco','Neuturmstrasse 1',5),
('Arthotel Munich','Germania','Monaco','Paul-Heyse-Strasse 10',3),
('Park Hyatt Sydney','Australia','Sydney','7 Hickson Road',5),
('Shangri-La Sydney','Australia','Sydney','176 Cumberland Street',5),
('Travelodge Hotel Sydney','Australia','Sydney','27 Wentworth Avenue',3),
('Park Hyatt Saigon','Vietnam','Ho Chi Minh','2 Lam Son Square',5),
('Hotel Nikko Saigon','Vietnam','Ho Chi Minh','235 Nguyen Van Cu',5),
('Silverland Yen Hotel','Vietnam','Ho Chi Minh','73-75 Thu Khoa Huan',4),
('Hotel Nikko Narita','Giappone','Narita','Tokko 500',4),
('Narita Tobu Hotel Airport','Giappone','Narita','Tokko 320-1',4),
('Richmond Hotel Narita','Giappone','Narita','Hanazaki-cho 970',3),
('Akra Hotel','Turchia','Antalya','Lara Yolu',5),
('Rixos Downtown Antalya','Turchia','Antalya','Sakip Sabanci Boulevard',5),
('Hotel Su & Aqualand','Turchia','Antalya','Meltem Mahallesi',4),
('The Merrion Hotel','Irlanda','Dublino','Upper Merrion Street',5),
('The Shelbourne Dublin','Irlanda','Dublino','St Stephens Green',5),
('Cassidys Hotel','Irlanda','Dublino','Cavendish Row',3),
('The Royal Sonesta Minneapolis','Stati Uniti','Minneapolis','35 South 7th Street',4),
('Hyatt Centric Downtown Minneapolis','Stati Uniti','Minneapolis','615 Second Avenue South',4),
('Moxy Minneapolis Downtown','Stati Uniti','Minneapolis','247 Chicago Avenue South',3),
('Four Seasons Riyadh','Arabia Saudita','Riyadh','Kingdom Centre',5),
('Riyadh Marriott Hotel','Arabia Saudita','Riyadh','King Saud Road',5),
('Centro Waha Riyadh','Arabia Saudita','Riyadh','Olaya Street',4),
('The Ritz-Carlton Fort Lauderdale','Stati Uniti','Fort Lauderdale','1 North Fort Lauderdale Beach Blvd',5),
('Pelican Grand Beach Resort','Stati Uniti','Fort Lauderdale','2000 North Ocean Boulevard',4),
('Hilton Fort Lauderdale Marina','Stati Uniti','Fort Lauderdale','1881 SE 17th Street',4),
('Park Hyatt Melbourne','Australia','Melbourne','1 Parliament Square',5),
('The Langham Melbourne','Australia','Melbourne','1 Southgate Avenue',5),
('Great Southern Hotel Melbourne','Australia','Melbourne','44 Spencer Street',3),
('Hotel Indonesia Kempinski','Indonesia','Jakarta','Jl. MH Thamrin 1',5),
('Grand Hyatt Jakarta','Indonesia','Jakarta','Jl. MH Thamrin',5),
('Ashley Wahid Hasyim','Indonesia','Jakarta','Jl. KH Wahid Hasyim',4),
('Four Seasons Hotel Ritz Lisbon','Portogallo','Lisbona','Rua Rodrigo da Fonseca 88',5),
('Corinthia Lisbon','Portogallo','Lisbona','Avenida Columbano Bordalo Pinheiro 105',5),
('HF Fenix Lisboa','Portogallo','Lisbona','Praca Marques de Pombal 8',4),
('Hotel Nixe Palace','Spagna','Palma di Maiorca','Avenida Joan Miro 269',5),
('Melia Palma Bay','Spagna','Palma di Maiorca','Calle Felicia Fuster 4',4),
('Hotel Amic Horizonte','Spagna','Palma di Maiorca','Vista Alegre 1',3),
('The Westin Book Cadillac','Stati Uniti','Detroit','1114 Washington Blvd',5),
('Detroit Marriott Renaissance Center','Stati Uniti','Detroit','Renaissance Center',4),
('The Siren Hotel','Stati Uniti','Detroit','1509 Broadway Street',4),
('Sofitel Legend Metropole Hanoi','Vietnam','Hanoi','15 Ngo Quyen',5),
('Apricot Hotel Hanoi','Vietnam','Hanoi','136 Hang Trong',5),
('Hanoi Pearl Hotel','Vietnam','Hanoi','6 Bao Khanh',4),
('The Edwardian Manchester','Regno Unito','Manchester','Free Trade Hall',5),
('Hotel Gotham Manchester','Regno Unito','Manchester','King Street 100',5),
('ibis Manchester Centre','Regno Unito','Manchester','Portland Street 96',3),
('Electra Metropolis Athens','Grecia','Atene','Mitropoleos 15',5),
('Athens Gate Hotel','Grecia','Atene','Syngrou Avenue 10',4),
('Divani Palace Acropolis','Grecia','Atene','Parthenonos 19',5),
('Hotel Sacher Wien','Austria','Vienna','Philharmoniker Strasse 4',5),
('Hilton Vienna Park','Austria','Vienna','Am Stadtpark 1',5),
('Motel One Wien Staatsoper','Austria','Vienna','Elisabethstrasse 5',3),
('Baur au Lac','Svizzera','Zurigo','Talstrasse 1',5),
('Park Hyatt Zurich','Svizzera','Zurigo','Beethovenstrasse 21',5),
('ibis Zurich City West','Svizzera','Zurigo','Schiffbaustrasse 11',3),
('The Ritz-Carlton Philadelphia','Stati Uniti','Philadelphia','10 Avenue of the Arts',5),
('Loews Philadelphia Hotel','Stati Uniti','Philadelphia','1200 Market Street',4),
('Club Quarters Philadelphia','Stati Uniti','Philadelphia','1628 Chestnut Street',3),
('Jinling Hotel Nanjing','Cina','Nanjing','Hanzhong Road 2',5),
('Shangri-La Nanjing','Cina','Nanjing','Zhongyang Road 329',5),
('Holiday Inn Nanjing Aqua City','Cina','Nanjing','Jiankang Road 1',4),
('The St. Regis Osaka','Giappone','Osaka','Honmachi 3-6-12',5),
('Conrad Osaka','Giappone','Osaka','Nakanoshima 3-2-4',5),
('Hotel Keihan Yodoyabashi','Giappone','Osaka','Kitahama 2-4-6',3),
('Hyatt Ziva Cancun','Messico','Cancùn','Blvd Kukulcan KM 9.5',5),
('Secrets The Vine Cancun','Messico','Cancùn','Blvd Kukulcan KM 14.5',5),
('Krystal Cancun','Messico','Cancùn','Paseo Kukulkan KM 9',4),
('Wanda Vista Changsha','Cina','Changsha','Yuelu District',5),
('Sheraton Changsha Hotel','Cina','Changsha','Furong Middle Road',5),
('Holiday Villa Changsha City Centre','Cina','Changsha','Furong District',4),
('Shangri-La Wuhan','Cina','Wuhan','700 Jianshe Avenue',5),
('Wuhan Marriott Hotel Optics Valley','Cina','Wuhan','797 Gaoxin Boulevard',5),
('Holiday Inn Wuhan Riverside','Cina','Wuhan','305 Zhongshan Road',4),
('NH Collection Copenhagen','Danimarca','Copenhagen','Strandgade 7',5),
('Copenhagen Marriott Hotel','Danimarca','Copenhagen','Kalvebod Brygge 5',5),
('Wakeup Copenhagen','Danimarca','Copenhagen','Borgergade 9',3),
('Grand Hyatt Jeju','Corea del Sud','Jeju','Noyeon-ro',5),
('Jeju Sun Hotel','Corea del Sud','Jeju','Sammu-ro',4),
('Ramada Plaza Jeju','Corea del Sud','Jeju','Tapdong-ro',5),
('Taj Krishna Hyderabad','India','Hyderabad','Road No.1 Banjara Hills',5),
('ITC Kohenur Hyderabad','India','Hyderabad','Madhapur',5),
('Lemon Tree Premier Hitec City','India','Hyderabad','Hitec City',4),
('Emirates Palace Mandarin Oriental','Emirati Arabi Uniti','Abu Dhabi','West Corniche Road',5),
('Hilton Abu Dhabi Yas Island','Emirati Arabi Uniti','Abu Dhabi','Yas Bay',5),
('Southern Sun Abu Dhabi','Emirati Arabi Uniti','Abu Dhabi','Al Mina Street',4),
('Marriott Mena House','Egitto','Il Cairo','Pyramids Road',5),
('Four Seasons Cairo at Nile Plaza','Egitto','Il Cairo','Garden City',5),
('Steigenberger Hotel El Tahrir','Egitto','Il Cairo','Kasr El Nile',4),
('JW Marriott Zhengzhou','Cina','Zhengzhou','Business Central Park',5),
('Hilton Zhengzhou','Cina','Zhengzhou','Jinshui Road',5),
('Holiday Inn Zhengzhou','Cina','Zhengzhou','Jingsan Road',4),
('Armani Hotel Milano','Italia','Milano','Via Manzoni 31',5),
('Excelsior Hotel Gallia','Italia','Milano','Piazza Duca dAosta 9',5),
('Hotel Berna','Italia','Milano','Via Napo Torriani 18',4),
('Grand America Hotel','Stati Uniti','Salt Lake City','555 South Main Street',5),
('Little America Hotel','Stati Uniti','Salt Lake City','500 South Main Street',4),
('Metropolitan Inn','Stati Uniti','Salt Lake City','524 South West Temple',3),
('Swiss Grand Xiamen','Cina','Xiamen','12 Lujiang Road',5),
('Langham Place Xiamen','Cina','Xiamen','4668 Xianyue Road',5),
('Ibis Xiamen Kaiyuan','Cina','Xiamen','870 Xiahe Road',3),
('Washington Dulles Airport Marriott','Stati Uniti','Dulles','45020 Aviation Drive',4),
('Hilton Washington Dulles Airport','Stati Uniti','Dulles','13869 Park Center Road',4),
('Hyatt Place Dulles Airport','Stati Uniti','Dulles','21481 Ridgetop Circle',3),
('Sagamore Pendry Baltimore','Stati Uniti','Baltimore','1715 Thames Street',5),
('Hyatt Regency Baltimore','Stati Uniti','Baltimore','300 Light Street',4),
('Lord Baltimore Hotel','Stati Uniti','Baltimore','20 West Baltimore Street',4),
('Hotel Okura Fukuoka','Giappone','Fukuoka','Hakata-ku Shimokawabatamachi 3-2',5),
('Grand Hyatt Fukuoka','Giappone','Fukuoka','Sumiyoshi 1-2-82',5),
('The B Hakata','Giappone','Fukuoka','Hakataeki Minami 1-3-9',3),
('Hilton Urumqi','Cina','Ürümqi','123 Hongguangshan Road',5),
('Universal Hotel Urumqi','Cina','Ürümqi','76 Beijing South Road',4),
('Jinjiang Inn Urumqi','Cina','Ürümqi','802 South Xinhua Road',3),
('The Hay-Adams','Stati Uniti','Washington DC','800 16th Street NW',5),
('Willard InterContinental','Stati Uniti','Washington DC','1401 Pennsylvania Ave NW',5),
('Washington Plaza Hotel','Stati Uniti','Washington DC','10 Thomas Circle NW',4),
('Shangri-La Qingdao','Cina','Qingdao','9 Xianggang Middle Road',5),
('The Westin Qingdao','Cina','Qingdao','8 Hong Kong Middle Road',5),
('Holiday Inn Qingdao City Centre','Cina','Qingdao','1 Xuzhou Road',4);

INSERT INTO CAMERA(numero, hotel, categoria, prezzo, max_ospiti, disponibilita)
VALUES
('401', 'The Ritz-Carlton Atlanta', 'Camera Standard', 199, 2, 'false'),
('1005', 'The Ritz-Carlton Atlanta', 'Family Suite', 380, 4, 'true'),
('2001', 'The Ritz-Carlton Atlanta', 'Presidential Suite', 840, 4, 'true'),
('421', 'Atlanta Marriott Marquis', 'Executive Room', 360, 2, 'true'),
('1011', 'Atlanta Marriott Marquis', 'Royal Room', 587, 3, 'true'),
('1301', 'Atlanta Marriott Marquis', 'Royal Suite', 695, 4, 'true'),
('516', 'Hyatt Regency Atlanta', 'Executive King Room', 241, 2, 'false'),
('901', 'Hyatt Regency Atlanta', 'Skyline Corner Suite', 410, 4, 'true'),
('401', 'Burj Al Arab Jumeirah', 'Elite Loft', 1342, 2, 'true'),
('720', 'Burj Al Arab Jumeirah', 'Cityview Room', 863, 2, 'true'),
('851', 'Burj Al Arab Jumeirah', 'Presidential Loft', 1196, 2, 'false'),
('101', 'Atlantis The Palm', 'Ocean Loft', 1456, 2, 'false'),
('401', 'Atlantis The Palm', 'Standard Penthouse', 1776, 4, 'true'),
('540', 'Atlantis The Palm', 'Deluxe Penthouse', 2498, 4, 'true'),
('301', 'Rove Downtown Dubai', 'Executive Room', 212, 2, 'true'),
('101', 'The Adolphus', 'Garden Loft', 305, 3, 'false'),
('401', 'The Adolphus', 'Elite Residence', 483, 2, 'false'),
('101', 'Omni Dallas Hotel', 'Premier Suite', 633, 4, 'false'),
('316', 'Omni Dallas Hotel', 'Executive Residence', 419, 2, 'true'),
('109', 'Magnolia Hotel Dallas', 'City Family Suite', 470, 2, 'false'),
('211', 'Magnolia Hotel Dallas', 'Signature Loft', 587, 3, 'true'),
('301', 'Magnolia Hotel Dallas', 'Signature Junior Suite', 595, 2, 'false'),
('423', 'The Ritz-Carlton Tokyo', 'Garden Penthouse', 467, 2, 'true'),
('601', 'The Ritz-Carlton Tokyo', 'Club Suite', 2442, 2, 'false'),
('611', 'The Ritz-Carlton Tokyo', 'Premier King Room', 1747, 2, 'false'),
('204', 'Park Hyatt Tokyo', 'Signature Suite', 2221, 2, 'true'),
('421', 'Park Hyatt Tokyo', 'Signature Loft', 1264, 3, 'false'),
('501', 'Park Hyatt Tokyo', 'Grand Suite', 2410, 3, 'true'),
('301', 'Hotel Gracery Shinjuku', 'Residence', 201, 2, 'false'),
('413', 'Hotel Gracery Shinjuku', 'Premier Loft', 299, 2, 'true'),
('221', 'The Savoy', 'Royal Suite', 968, 4, 'true'),
('501', 'The Savoy', 'Ocean Studio', 1194, 3, 'true'),
('301', 'The Langham London', 'Executive King Room', 1907, 2, 'true'),
('551', 'The Langham London', 'Royal Corner Suite', 1609, 2, 'true'),
('716', 'The Langham London', 'Grand Queen Room', 1995, 4, 'false'),
('201', 'Point A Hotel Westminster', 'Grand King Room', 85, 2, 'false'),
('307', 'The Brown Palace', 'Panorama Family Suite', 1831, 2, 'true'),
('401', 'The Brown Palace', 'Ocean Family Suite', 2178, 2, 'false'),
('526', 'The Brown Palace', 'Royal Residence', 2307, 2, 'false'),
('220', 'Hyatt Regency Denver', 'Ocean Penthouse', 524, 2, 'false'),
('421', 'Hyatt Regency Denver', 'City Residence', 473, 4, 'false'),
('101', 'Hampton Inn Downtown Denver', 'Executive Corner Suite', 152, 2, 'true'),
('214', 'Ciragan Palace Kempinski', 'Heritage Suite', 1185, 2, 'false'),
('303', 'Ciragan Palace Kempinski', 'Signature King Room', 451, 2, 'false'),
('110', 'The Marmara Taksim', 'Royal Studio', 303, 3, 'false'),
('116', 'The Marmara Taksim', 'Signature King Room', 205, 3, 'true'),
('201', 'Hotel Amira Istanbul', 'Panorama Queen Room', 378, 2, 'true'),
('401', 'Hotel Amira Istanbul', 'City Suite', 141, 2, 'true'),
('317', 'The Peninsula Chicago', 'Grand Suite', 2308, 2, 'false'),
('511', 'The Peninsula Chicago', 'Grand Studio', 1021, 2, 'false'),
('613', 'The Peninsula Chicago', 'Grand Residence', 2476, 2, 'false'),
('501', 'The Langham Chicago', 'Grand Suite', 1170, 2, 'false'),
('207', 'Congress Plaza Hotel', 'Royal Corner Suite', 255, 2, 'true'),
('401', 'The Imperial New Delhi', 'Signature Suite', 191, 2, 'false'),
('618', 'The Imperial New Delhi', 'Garden Junior Suite', 559, 3, 'true'),
('701', 'The Imperial New Delhi', 'Heritage Penthouse', 570, 2, 'true'),
('201', 'Taj Palace New Delhi', 'Elite Queen Room', 830, 3, 'true'),
('415', 'Taj Palace New Delhi', 'Grand Corner Suite', 1147, 4, 'true'),
('121', 'The Connaught New Delhi', 'Heritage Penthouse', 513, 2, 'true'),
('301', 'The Connaught New Delhi', 'Royal Family Suite', 649, 2, 'true'),
('317', 'The Peninsula Shanghai', 'Elite Loft', 2566, 3, 'true'),
('606', 'The Peninsula Shanghai', 'Signature King Room', 832, 3, 'true'),
('212', 'Fairmont Peace Hotel', 'Signature Queen Room', 547, 3, 'false'),
('505', 'Fairmont Peace Hotel', 'Skyline Residence', 597, 2, 'true'),
('801', 'Fairmont Peace Hotel', 'City Residence', 409, 2, 'true'),
('308', 'Holiday Inn Shanghai Nanjing Road', 'Signature Loft', 577, 2, 'false'),
('721', 'The Beverly Hills Hotel', 'Skyline Studio', 445, 2, 'true'),
('312', 'InterContinental Los Angeles Downtown', 'Garden Loft', 572, 2, 'false'),
('605', 'InterContinental Los Angeles Downtown', 'Executive Queen Room', 504, 4, 'true'),
('210', 'Hollywood Hotel', 'Premier Penthouse', 340, 4, 'false'),
('409', 'Hollywood Hotel', 'Garden Family Suite', 458, 4, 'true'),
('111', 'Four Seasons Guangzhou', 'Panorama Queen Room', 1832, 2, 'false'),
('509', 'Four Seasons Guangzhou', 'Elite Studio', 1403, 4, 'true'),
('319', 'The Ritz-Carlton Guangzhou', 'Deluxe Corner Suite', 1326, 2, 'false'),
('602', 'The Ritz-Carlton Guangzhou', 'Grand Family Suite', 2240, 3, 'false'),
('105', 'Guangzhou Marriott Tianhe', 'Executive Studio', 645, 2, 'false'),
('231', 'Signiel Seoul', 'Panorama Junior Suite', 493, 2, 'false'),
('410', 'Signiel Seoul', 'Skyline King Room', 488, 3, 'true'),
('406', 'Four Seasons Hotel Seoul', 'Elite Queen Room', 2657, 2, 'true'),
('141', 'LOTTE City Hotel Myeongdong', 'Heritage Corner Suite', 294, 4, 'true'),
('226', 'LOTTE City Hotel Myeongdong', 'Skyline Corner Suite', 146, 2, 'false'),
('316', 'Le Bristol Paris', 'Garden Studio', 248, 4, 'false'),
('501', 'Le Bristol Paris', 'Skyline Penthouse', 464, 2, 'false'),
('212', 'Hotel Lutetia Paris', 'Deluxe King Room', 144, 2, 'false'),
('146', 'Novotel Paris Centre Tour Eiffel', 'Skyline Family Suite', 426, 4, 'false'),
('301', 'Novotel Paris Centre Tour Eiffel', 'Ocean Queen Room', 156, 2, 'false'),
('401', 'Novotel Paris Centre Tour Eiffel', 'Deluxe Corner Suite', 329, 2, 'true'),
('311', 'Marina Bay Sands', 'Club Residence', 290, 2, 'false'),
('416', 'Marina Bay Sands', 'Heritage Family Suite', 565, 3, 'true'),
('607', 'Marina Bay Sands', 'Deluxe Queen Room', 378, 2, 'false'),
('129', 'The Fullerton Hotel Singapore', 'Elite Studio', 244, 4, 'false'),
('501', 'The Fullerton Hotel Singapore', 'Club Corner Suite', 268, 4, 'true'),
('526', 'The Fullerton Hotel Singapore', 'Ocean King Room', 596, 3, 'false'),
('238', 'Hotel Boss', 'Premier Penthouse', 196, 2, 'false'),
('411', 'Waldorf Astoria Beijing', 'Ocean King Room', 2643, 2, 'false'),
('521', 'Waldorf Astoria Beijing', 'Grand Family Suite', 2022, 2, 'true'),
('256', 'Grand Hyatt Beijing', 'Skyline King Room', 400, 3, 'true'),
('401', 'Grand Hyatt Beijing', 'Garden Queen Room', 596, 3, 'false'),
('503', 'Grand Hyatt Beijing', 'Grand Corner Suite', 331, 2, 'false'),
('601', 'Grand Hyatt Beijing', 'Panorama Corner Suite', 371, 2, 'true'),
('221', 'Novotel Beijing Peace', 'Premier Family Suite', 568, 2, 'true'),
('142', 'Kimpton De Witt Amsterdam', 'City Penthouse', 225, 2, 'false'),
('211', 'Kimpton De Witt Amsterdam', 'Signature Junior Suite', 296, 3, 'false'),
('126', 'Park Plaza Victoria Amsterdam', 'Grand Penthouse', 583, 4, 'false'),
('219', 'NH Collection Amsterdam Barbizon Palace', 'Premier Residence', 2341, 2, 'true'),
('310', 'NH Collection Amsterdam Barbizon Palace', 'Ocean Residence', 2233, 4, 'true'),
('220', 'The Westin Palace Madrid', 'Garden Suite', 584, 4, 'false'),
('301', 'The Westin Palace Madrid', 'City Penthouse', 1321, 2, 'true'),
('415', 'The Westin Palace Madrid', 'Premier King Room', 1851, 2, 'false'),
('116', 'Mandarin Oriental Ritz Madrid', 'City Suite', 1888, 2, 'false'),
('250', 'Mandarin Oriental Ritz Madrid', 'Deluxe Queen Room', 1438, 3, 'false'),
('301', 'Mandarin Oriental Ritz Madrid', 'Executive Residence', 2702, 4, 'false'),
('401', 'Hotel Regina Madrid', 'Garden Loft', 568, 2, 'true'),
('205', 'The Plaza Hotel', 'Premier Queen Room', 396, 2, 'false'),
('608', 'The Plaza Hotel', 'Heritage Family Suite', 495, 2, 'false'),
('720', 'The St. Regis New York', 'Executive Queen Room', 2280, 2, 'false'),
('411', 'Pod Times Square', 'Grand Studio', 471, 2, 'false'),
('410', 'Mandarin Oriental Bangkok', 'Garden Studio', 659, 2, 'true'),
('601', 'Mandarin Oriental Bangkok', 'Elite Suite', 1163, 2, 'false'),
('319', 'Shangri-La Bangkok', 'City Residence', 173, 2, 'true'),
('507', 'Shangri-La Bangkok', 'Club Corner Suite', 634, 2, 'true'),
('219', 'Amara Bangkok Hotel', 'Premier Corner Suite', 608, 2, 'false'),
('410', 'Amara Bangkok Hotel', 'Skyline Loft', 590, 3, 'true'),
('415', 'Steigenberger Frankfurter Hof', 'Deluxe Junior Suite', 245, 2, 'false'),
('757', 'JW Marriott Hotel Frankfurt', 'Deluxe Queen Room', 202, 2, 'true'),
('704', 'JW Marriott Hotel Frankfurt', 'Deluxe Studio', 487, 2, 'true'),
('161', 'Moxy Frankfurt City Center', 'City Residence', 210, 4, 'false'),
('650', 'The Ritz-Carlton Shenzhen', 'Panorama Family Suite', 632, 2, 'false'),
('599', 'The Ritz-Carlton Shenzhen', 'Ocean Penthouse', 974, 2, 'false'),
('394', 'Four Seasons Shenzhen', 'Club Corner Suite', 1814, 2, 'false'),
('168', 'Four Seasons Shenzhen', 'Heritage Studio', 1890, 3, 'false'),
('663', 'Hyatt Place Shenzhen Airport', 'Signature Family Suite', 281, 2, 'false'),
('320', 'Hyatt Place Shenzhen Airport', 'Royal Residence', 595, 2, 'false'),
('666', 'The Ritz-Carlton Charlotte', 'Premier Suite', 662, 4, 'false'),
('506', 'The Ritz-Carlton Charlotte', 'City Residence', 2693, 4, 'true'),
('190', 'Grand Bohemian Charlotte', 'Ocean Suite', 241, 2, 'false'),
('143', 'Grand Bohemian Charlotte', 'Signature Junior Suite', 299, 4, 'false'),
('234', 'Grand Bohemian Charlotte', 'City Corner Suite', 475, 2, 'true'),
('308', 'Hilton Charlotte Uptown', 'Ocean Family Suite', 318, 2, 'false'),
('913', 'Bellagio Las Vegas', 'City Queen Room', 581, 3, 'false'),
('332', 'Bellagio Las Vegas', 'Garden Residence', 411, 2, 'true'),
('755', 'The Venetian Resort', 'Signature Residence', 545, 4, 'true'),
('582', 'The Venetian Resort', 'Garden Family Suite', 354, 3, 'true'),
('166', 'The Venetian Resort', 'Heritage Loft', 502, 2, 'true'),
('617', 'Excalibur Hotel & Casino', 'Grand Queen Room', 262, 4, 'false'),
('518', 'Waldorf Astoria Orlando', 'Ocean Studio', 1964, 3, 'true'),
('160', 'Waldorf Astoria Orlando', 'Panorama Suite', 2697, 3, 'false'),
('673', 'Hyatt Regency Orlando', 'Club Studio', 473, 2, 'true'),
('218', 'Avanti International Resort', 'Elite Suite', 394, 2, 'false'),
('462', 'Mandarin Oriental Kuala Lumpur', 'Panorama Family Suite', 2316, 2, 'false'),
('675', 'Mandarin Oriental Kuala Lumpur', 'Panorama Suite', 2528, 2, 'false'),
('105', 'Grand Hyatt Kuala Lumpur', 'Elite Queen Room', 261, 2, 'true'),
('518', 'Grand Hyatt Kuala Lumpur', 'Heritage Queen Room', 632, 4, 'true'),
('985', 'Hotel Sentral KL', 'Panorama Corner Suite', 270, 2, 'true'),
('942', 'Fontainebleau Miami Beach', 'Signature Suite', 609, 2, 'true'),
('724', 'Fontainebleau Miami Beach', 'Heritage Studio', 217, 2, 'true'),
('857', 'EAST Miami', 'Premier Junior Suite', 641, 3, 'true'),
('792', 'EAST Miami', 'City Penthouse', 311, 2, 'true'),
('626', 'EAST Miami', 'Ocean Loft', 284, 3, 'false'),
('423', 'YVE Hotel Miami', 'Signature Loft', 152, 2, 'false'),
('354', 'YVE Hotel Miami', 'Panorama Residence', 97, 4, 'false'),
('760', 'The Taj Mahal Palace', 'Deluxe Penthouse', 1140, 2, 'true'),
('151', 'The Taj Mahal Palace', 'Club Family Suite', 996, 2, 'false'),
('356', 'Trident Nariman Point', 'Panorama Residence', 159, 2, 'true'),
('895', 'Trident Nariman Point', 'Premier Queen Room', 393, 4, 'true'),
('730', 'President Mumbai', 'Premier Studio', 392, 2, 'true'),
('515', 'President Mumbai', 'Skyline Studio', 641, 2, 'true'),
('735', 'Majestic Hotel & Spa Barcelona', 'Signature Junior Suite', 366, 4, 'true'),
('557', 'Majestic Hotel & Spa Barcelona', 'Ocean Loft', 341, 4, 'false'),
('924', 'Majestic Hotel & Spa Barcelona', 'Premier Corner Suite', 598, 4, 'false'),
('880', 'Hotel Arts Barcelona', 'Signature Loft', 183, 4, 'false'),
('886', 'Hotel Arts Barcelona', 'Panorama Queen Room', 472, 2, 'true'),
('347', 'Catalonia Ramblas', 'Skyline Suite', 225, 2, 'true'),
('332', 'Catalonia Ramblas', 'Garden King Room', 173, 2, 'false'),
('874', 'Niccolo Chengdu', 'Premier Residence', 549, 3, 'true'),
('455', 'Niccolo Chengdu', 'Elite Corner Suite', 299, 3, 'true'),
('209', 'The Ritz-Carlton Chengdu', 'Deluxe King Room', 2458, 2, 'false'),
('539', 'The Ritz-Carlton Chengdu', 'Executive Junior Suite', 2610, 2, 'false'),
('803', 'Holiday Inn Chengdu Century City', 'Grand Penthouse', 168, 2, 'false'),
('363', 'The Peninsula Hong Kong', 'Deluxe Loft', 2147, 2, 'true'),
('347', 'The Peninsula Hong Kong', 'Premier Residence', 2401, 2, 'true'),
('984', 'Mandarin Oriental Hong Kong', 'Panorama Junior Suite', 2743, 3, 'false'),
('420', 'Mandarin Oriental Hong Kong', 'Panorama Junior Suite', 2681, 2, 'true'),
('748', 'B P International', 'Royal Suite', 278, 2, 'false'),
('813', 'B P International', 'Ocean Family Suite', 493, 4, 'false'),
('175', 'Fairmont Olympic Hotel', 'City Studio', 517, 2, 'false'),
('175', 'Grand Hyatt Seattle', 'Premier Residence', 203, 2, 'false'),
('960', 'Grand Hyatt Seattle', 'City Queen Room', 161, 2, 'true'),
('991', 'Grand Hyatt Seattle', 'City Family Suite', 203, 3, 'false'),
('337', 'The Belltown Inn', 'Grand Loft', 535, 2, 'true'),
('881', 'Mandarin Oriental Doha', 'Ocean Family Suite', 873, 2, 'true'),
('521', 'Mandarin Oriental Doha', 'City Family Suite', 1193, 2, 'false'),
('774', 'Mandarin Oriental Doha', 'Panorama Residence', 2215, 4, 'true'),
('329', 'JW Marriott Marquis City Center Doha', 'Signature Corner Suite', 384, 2, 'true'),
('785', 'JW Marriott Marquis City Center Doha', 'Club Junior Suite', 296, 2, 'true'),
('638', 'JW Marriott Marquis City Center Doha', 'Panorama King Room', 152, 2, 'false'),
('363', 'Millennium Central Doha', 'City Loft', 386, 2, 'false'),
('709', 'Millennium Central Doha', 'Elite Junior Suite', 340, 2, 'false'),
('517', 'Arizona Biltmore', 'Skyline Junior Suite', 433, 4, 'false'),
('903', 'JW Marriott Phoenix Desert Ridge', 'Deluxe Junior Suite', 398, 2, 'true'),
('992', 'JW Marriott Phoenix Desert Ridge', 'Skyline Queen Room', 366, 4, 'true'),
('239', 'Hilton Garden Inn Phoenix Airport', 'Deluxe Suite', 551, 2, 'false'),
('357', 'Fairmont San Francisco', 'Panorama Family Suite', 311, 2, 'false'),
('366', 'Fairmont San Francisco', 'Deluxe Residence', 549, 2, 'true'),
('644', 'InterContinental San Francisco', 'City Loft', 371, 2, 'false'),
('803', 'InterContinental San Francisco', 'Heritage Junior Suite', 579, 2, 'true'),
('875', 'Hotel Stratford', 'Signature Loft', 336, 4, 'false'),
('931', 'Hotel Stratford', 'Panorama Loft', 602, 2, 'false'),
('160', 'The Manila Hotel', 'Heritage Residence', 490, 2, 'true'),
('511', 'The Manila Hotel', 'Grand Queen Room', 591, 2, 'true'),
('533', 'New World Makati Hotel', 'Heritage Studio', 531, 4, 'true'),
('562', 'New World Makati Hotel', 'Executive Family Suite', 443, 4, 'true'),
('307', 'Red Planet Manila Bay', 'Royal Suite', 105, 2, 'true'),
('526', 'Hotel Eden', 'Skyline King Room', 288, 3, 'false'),
('743', 'Hotel Eden', 'Ocean Junior Suite', 200, 4, 'true'),
('797', 'Hotel Eden', 'Deluxe King Room', 359, 4, 'true'),
('388', 'Anantara Palazzo Naiadi', 'Elite Loft', 450, 2, 'false'),
('674', 'Anantara Palazzo Naiadi', 'Grand Family Suite', 490, 4, 'false'),
('806', 'UNAHOTELS Decò Roma', 'Garden King Room', 547, 3, 'true'),
('354', 'UNAHOTELS Decò Roma', 'Garden King Room', 472, 2, 'true'),
('520', 'Grand Hyatt Taipei', 'City Queen Room', 392, 2, 'true'),
('659', 'Grand Hyatt Taipei', 'Garden King Room', 441, 4, 'false'),
('124', 'Taipei Marriott Hotel', 'Club Residence', 304, 4, 'false'),
('467', 'Taipei Marriott Hotel', 'Club Queen Room', 203, 2, 'false'),
('333', 'City Suites Taipei', 'Signature Loft', 174, 3, 'true'),
('346', 'The Ritz-Carlton Jeddah', 'Skyline Family Suite', 2211, 3, 'false'),
('496', 'The Ritz-Carlton Jeddah', 'Club Penthouse', 529, 4, 'false'),
('885', 'Rosewood Jeddah', 'Ocean Suite', 584, 2, 'false'),
('687', 'Rosewood Jeddah', 'Club King Room', 258, 2, 'false'),
('367', 'Rosewood Jeddah', 'Ocean Loft', 589, 2, 'false'),
('240', 'Centro Shaheen Jeddah', 'Signature Studio', 463, 2, 'true'),
('580', 'Centro Shaheen Jeddah', 'Garden Studio', 146, 3, 'false'),
('704', 'DoubleTree by Hilton Newark Penn Station', 'Deluxe Studio', 190, 2, 'false'),
('418', 'TRYP by Wyndham Newark Downtown', 'Ocean Corner Suite', 153, 2, 'true'),
('210', 'Courtyard Newark Downtown', 'Executive Studio', 645, 3, 'true'),
('492', 'Niccolo Chongqing', 'City Family Suite', 547, 2, 'true'),
('790', 'Niccolo Chongqing', 'Grand Suite', 605, 2, 'true'),
('595', 'Niccolo Chongqing', 'Panorama King Room', 510, 2, 'false'),
('357', 'Hilton Chongqing', 'Grand Suite', 540, 2, 'true'),
('342', 'Hilton Chongqing', 'Skyline Studio', 455, 2, 'true'),
('169', 'Glenview ITC Plaza Chongqing', 'City Penthouse', 288, 2, 'false'),
('608', 'Glenview ITC Plaza Chongqing', 'Royal Corner Suite', 425, 2, 'false'),
('879', 'The Post Oak Hotel', 'Deluxe Queen Room', 266, 4, 'true'),
('647', 'The Post Oak Hotel', 'Royal Residence', 469, 2, 'false'),
('347', 'Hilton Americas Houston', 'Ocean Queen Room', 520, 2, 'false'),
('666', 'Hilton Americas Houston', 'Elite Family Suite', 417, 2, 'false'),
('712', 'Club Quarters Houston', 'Executive Penthouse', 507, 3, 'true'),
('596', 'Club Quarters Houston', 'Garden Residence', 628, 2, 'false'),
('866', 'Four Seasons Hangzhou at West Lake', 'Heritage Junior Suite', 1668, 2, 'false'),
('484', 'Four Seasons Hangzhou at West Lake', 'City Suite', 2040, 3, 'false'),
('576', 'Four Seasons Hangzhou at West Lake', 'Royal King Room', 534, 2, 'false'),
('565', 'Grand Hyatt Hangzhou', 'Royal Corner Suite', 223, 2, 'false'),
('655', 'Grand Hyatt Hangzhou', 'Garden Junior Suite', 562, 3, 'false'),
('180', 'Holiday Inn Hangzhou CBD', 'Panorama Penthouse', 583, 4, 'true'),
('454', 'Sofitel Kunming', 'Club Loft', 548, 3, 'true'),
('921', 'Crowne Plaza Kunming City Centre', 'Royal Corner Suite', 472, 2, 'false'),
('554', 'Crowne Plaza Kunming City Centre', 'Grand Loft', 626, 4, 'true'),
('310', 'Fairyland Hotel Kunming', 'Heritage King Room', 623, 2, 'false'),
('268', 'Novotel Xianyang International Airport', 'Ocean Family Suite', 338, 2, 'true'),
('341', 'Licai Tianxi Hotel', 'Elite King Room', 353, 3, 'true'),
('172', 'Xianyang Ocean Spring Hotel', 'Royal Loft', 388, 2, 'false'),
('984', 'Fairmont Royal York', 'Heritage Loft', 236, 3, 'false'),
('392', 'Fairmont Royal York', 'Grand Penthouse', 142, 2, 'false'),
('103', 'The Ritz-Carlton Toronto', 'Club Loft', 1316, 2, 'false'),
('492', 'The Ritz-Carlton Toronto', 'Deluxe Loft', 2528, 2, 'false'),
('924', 'Chelsea Hotel Toronto', 'Garden Residence', 246, 2, 'true'),
('713', 'Chelsea Hotel Toronto', 'Premier Family Suite', 370, 4, 'true'),
('572', 'Grand Hyatt Bogota', 'City Suite', 311, 2, 'false'),
('209', 'Grand Hyatt Bogota', 'Panorama Queen Room', 467, 2, 'false'),
('234', 'Grand Hyatt Bogota', 'Panorama Penthouse', 404, 3, 'true'),
('626', 'Hilton Bogota', 'Premier Penthouse', 479, 4, 'false'),
('525', 'Hotel Estelar La Fontana', 'Skyline Penthouse', 601, 2, 'false'),
('969', 'Four Seasons Hotel Mexico City', 'Deluxe Junior Suite', 2272, 3, 'true'),
('121', 'Four Seasons Hotel Mexico City', 'Premier Family Suite', 460, 2, 'false'),
('966', 'Hyatt Regency Mexico City', 'Panorama Loft', 582, 3, 'false'),
('512', 'Hyatt Regency Mexico City', 'Panorama Queen Room', 530, 2, 'false'),
('912', 'Hotel Castropol', 'City Penthouse', 554, 2, 'false'),
('862', 'Boston Harbor Hotel', 'City Penthouse', 399, 4, 'false'),
('582', 'The Langham Boston', 'City Suite', 1764, 2, 'false'),
('906', 'The Langham Boston', 'Signature Loft', 2686, 4, 'true'),
('377', 'The Langham Boston', 'City Corner Suite', 2477, 4, 'false'),
('663', 'Club Quarters Hotel Boston', 'Signature Suite', 275, 3, 'false'),
('130', 'Hotel Fasano São Paulo', 'City Loft', 174, 4, 'true'),
('980', 'Renaissance São Paulo Hotel', 'Royal Family Suite', 169, 4, 'false'),
('733', 'Renaissance São Paulo Hotel', 'Royal Loft', 392, 3, 'false'),
('761', 'Ibis Paulista', 'Heritage Residence', 143, 2, 'false'),
('390', 'The Ritz-Carlton Moscow', 'Panorama King Room', 966, 2, 'false'),
('592', 'The Ritz-Carlton Moscow', 'City Suite', 2149, 2, 'false'),
('401', 'The Ritz-Carlton Moscow', 'Royal Corner Suite', 849, 3, 'true'),
('851', 'Metropol Moscow', 'Panorama Loft', 601, 2, 'true'),
('186', 'Metropol Moscow', 'Executive Family Suite', 211, 4, 'false'),
('742', 'Metropol Moscow', 'City Junior Suite', 247, 2, 'true'),
('950', 'Holiday Inn Moscow Sokolniki', 'Skyline Queen Room', 212, 2, 'false'),
('116', 'The Leela Palace Bengaluru', 'Premier Residence', 1155, 2, 'false'),
('742', 'The Leela Palace Bengaluru', 'Garden Family Suite', 2414, 3, 'true'),
('254', 'ITC Gardenia Bengaluru', 'Skyline King Room', 249, 2, 'true'),
('105', 'ITC Gardenia Bengaluru', 'Heritage Penthouse', 330, 3, 'true'),
('249', 'The Chancery Pavilion', 'Heritage Studio', 506, 2, 'true'),
('200', 'Hotel Bayerischer Hof', 'Deluxe Penthouse', 349, 3, 'true'),
('836', 'Mandarin Oriental Munich', 'Garden Loft', 1776, 2, 'true'),
('482', 'Mandarin Oriental Munich', 'Premier Penthouse', 1603, 4, 'false'),
('971', 'Arthotel Munich', 'Heritage Residence', 504, 2, 'true'),
('667', 'Park Hyatt Sydney', 'Club Queen Room', 2009, 4, 'true'),
('296', 'Park Hyatt Sydney', 'Ocean Corner Suite', 1040, 2, 'false'),
('331', 'Shangri-La Sydney', 'Garden Residence', 513, 2, 'false'),
('809', 'Shangri-La Sydney', 'Grand King Room', 475, 2, 'true'),
('128', 'Shangri-La Sydney', 'Garden Corner Suite', 166, 2, 'false'),
('205', 'Travelodge Hotel Sydney', 'Grand Junior Suite', 102, 2, 'true'),
('597', 'Park Hyatt Saigon', 'Ocean Corner Suite', 1723, 3, 'false'),
('669', 'Park Hyatt Saigon', 'Panorama Studio', 2541, 4, 'false'),
('580', 'Hotel Nikko Saigon', 'Garden Junior Suite', 640, 2, 'true'),
('216', 'Silverland Yen Hotel', 'Skyline Residence', 350, 2, 'false'),
('739', 'Silverland Yen Hotel', 'Executive King Room', 473, 2, 'false'),
('692', 'Hotel Nikko Narita', 'Elite Loft', 443, 2, 'true'),
('778', 'Hotel Nikko Narita', 'Deluxe Family Suite', 556, 2, 'false'),
('264', 'Narita Tobu Hotel Airport', 'Executive Suite', 147, 2, 'false'),
('306', 'Richmond Hotel Narita', 'Club Family Suite', 622, 2, 'true'),
('637', 'Akra Hotel', 'Signature King Room', 631, 2, 'true'),
('471', 'Akra Hotel', 'Elite Corner Suite', 556, 2, 'true'),
('161', 'Rixos Downtown Antalya', 'City Junior Suite', 345, 2, 'false'),
('679', 'Hotel Su & Aqualand', 'Grand Queen Room', 405, 3, 'true'),
('212', 'The Merrion Hotel', 'Signature King Room', 204, 2, 'false'),
('211', 'The Merrion Hotel', 'Ocean Junior Suite', 316, 3, 'true'),
('398', 'The Shelbourne Dublin', 'Royal Suite', 299, 2, 'true'),
('498', 'The Shelbourne Dublin', 'Elite Suite', 642, 4, 'false'),
('119', 'Cassidys Hotel', 'Heritage Residence', 458, 4, 'true'),
('669', 'The Royal Sonesta Minneapolis', 'Grand Residence', 647, 2, 'true'),
('924', 'The Royal Sonesta Minneapolis', 'Heritage Family Suite', 220, 4, 'true'),
('934', 'The Royal Sonesta Minneapolis', 'Elite Suite', 330, 2, 'true'),
('303', 'Hyatt Centric Downtown Minneapolis', 'Garden Suite', 158, 3, 'true'),
('177', 'Hyatt Centric Downtown Minneapolis', 'Garden Residence', 338, 2, 'false'),
('763', 'Moxy Minneapolis Downtown', 'Deluxe Penthouse', 143, 2, 'true'),
('819', 'Four Seasons Riyadh', 'Premier Family Suite', 2127, 2, 'false'),
('533', 'Four Seasons Riyadh', 'Club Junior Suite', 2644, 2, 'true'),
('645', 'Four Seasons Riyadh', 'Executive Residence', 484, 2, 'false'),
('928', 'Riyadh Marriott Hotel', 'Premier Family Suite', 314, 4, 'false'),
('854', 'Riyadh Marriott Hotel', 'Executive Suite', 251, 2, 'true'),
('550', 'Riyadh Marriott Hotel', 'Garden Corner Suite', 644, 3, 'true'),
('562', 'Centro Waha Riyadh', 'Heritage Penthouse', 161, 2, 'true'),
('560', 'Centro Waha Riyadh', 'City Residence', 524, 2, 'true'),
('999', 'The Ritz-Carlton Fort Lauderdale', 'Garden Queen Room', 2695, 3, 'true'),
('785', 'The Ritz-Carlton Fort Lauderdale', 'Elite Residence', 1370, 4, 'true'),
('471', 'Pelican Grand Beach Resort', 'Heritage Loft', 509, 4, 'false'),
('279', 'Pelican Grand Beach Resort', 'Club Corner Suite', 153, 3, 'false'),
('872', 'Hilton Fort Lauderdale Marina', 'Ocean Loft', 559, 2, 'true'),
('785', 'Park Hyatt Melbourne', 'Ocean Corner Suite', 1380, 3, 'true'),
('357', 'Park Hyatt Melbourne', 'Royal Loft', 2087, 3, 'true'),
('816', 'The Langham Melbourne', 'Elite Family Suite', 526, 3, 'false'),
('308', 'The Langham Melbourne', 'Skyline Corner Suite', 657, 2, 'false'),
('776', 'Great Southern Hotel Melbourne', 'Premier King Room', 496, 2, 'false'),
('964', 'Great Southern Hotel Melbourne', 'City Junior Suite', 271, 2, 'false'),
('899', 'Hotel Indonesia Kempinski', 'Club Residence', 624, 4, 'true'),
('579', 'Hotel Indonesia Kempinski', 'Executive Residence', 366, 4, 'false'),
('323', 'Grand Hyatt Jakarta', 'Club Penthouse', 454, 2, 'false'),
('571', 'Grand Hyatt Jakarta', 'Premier Penthouse', 510, 2, 'false'),
('912', 'Ashley Wahid Hasyim', 'Executive Loft', 141, 4, 'true'),
('879', 'Four Seasons Hotel Ritz Lisbon', 'Elite Residence', 1125, 2, 'true'),
('680', 'Four Seasons Hotel Ritz Lisbon', 'Skyline Corner Suite', 1892, 3, 'false'),
('634', 'Corinthia Lisbon', 'Signature Residence', 458, 3, 'true'),
('386', 'Corinthia Lisbon', 'Club Junior Suite', 436, 2, 'true'),
('795', 'Corinthia Lisbon', 'Garden King Room', 363, 2, 'false'),
('364', 'HF Fenix Lisboa', 'Deluxe Family Suite', 342, 4, 'false'),
('447', 'HF Fenix Lisboa', 'Heritage Suite', 318, 2, 'false'),
('510', 'Hotel Nixe Palace', 'Signature Suite', 1083, 3, 'false'),
('253', 'Hotel Nixe Palace', 'Club Junior Suite', 1361, 2, 'true'),
('831', 'Melia Palma Bay', 'Garden Junior Suite', 474, 3, 'true'),
('139', 'Hotel Amic Horizonte', 'Ocean Studio', 354, 2, 'false'),
('271', 'The Westin Book Cadillac', 'Royal Residence', 290, 2, 'false'),
('280', 'Detroit Marriott Renaissance Center', 'Royal King Room', 224, 2, 'false'),
('606', 'Detroit Marriott Renaissance Center', 'Heritage Corner Suite', 279, 2, 'true'),
('882', 'The Siren Hotel', 'Ocean Suite', 589, 2, 'true'),
('552', 'Sofitel Legend Metropole Hanoi', 'Ocean Corner Suite', 465, 2, 'true'),
('925', 'Sofitel Legend Metropole Hanoi', 'Panorama King Room', 403, 2, 'true'),
('837', 'Apricot Hotel Hanoi', 'Grand Residence', 632, 3, 'true'),
('961', 'Apricot Hotel Hanoi', 'Grand Suite', 323, 2, 'true'),
('169', 'Hanoi Pearl Hotel', 'Grand King Room', 348, 2, 'false'),
('969', 'Hanoi Pearl Hotel', 'Signature Residence', 550, 2, 'true'),
('164', 'Hanoi Pearl Hotel', 'Heritage Queen Room', 371, 3, 'true'),
('307', 'The Edwardian Manchester', 'Elite Penthouse', 371, 2, 'false'),
('286', 'The Edwardian Manchester', 'Executive Penthouse', 419, 2, 'false'),
('932', 'The Edwardian Manchester', 'Signature Corner Suite', 638, 2, 'false'),
('761', 'Hotel Gotham Manchester', 'Elite Junior Suite', 322, 2, 'true'),
('644', 'Hotel Gotham Manchester', 'Premier Family Suite', 326, 2, 'false'),
('584', 'Hotel Gotham Manchester', 'Heritage Queen Room', 597, 2, 'false'),
('703', 'ibis Manchester Centre', 'Grand Corner Suite', 211, 3, 'true'),
('565', 'Electra Metropolis Athens', 'Elite King Room', 630, 3, 'false'),
('290', 'Electra Metropolis Athens', 'City Junior Suite', 479, 3, 'true'),
('848', 'Electra Metropolis Athens', 'Club King Room', 563, 4, 'true'),
('889', 'Athens Gate Hotel', 'Premier Queen Room', 592, 2, 'true'),
('383', 'Divani Palace Acropolis', 'Premier Family Suite', 828, 2, 'true'),
('507', 'Divani Palace Acropolis', 'Grand Junior Suite', 955, 3, 'true'),
('931', 'Hotel Sacher Wien', 'Elite Queen Room', 568, 4, 'true'),
('789', 'Hotel Sacher Wien', 'City Studio', 594, 2, 'true'),
('338', 'Hilton Vienna Park', 'Garden Family Suite', 588, 2, 'true'),
('928', 'Hilton Vienna Park', 'Royal Penthouse', 537, 2, 'false'),
('673', 'Motel One Wien Staatsoper', 'Signature Family Suite', 491, 2, 'false'),
('179', 'Baur au Lac', 'Heritage Queen Room', 633, 2, 'false'),
('848', 'Baur au Lac', 'Signature Residence', 166, 3, 'true'),
('706', 'Baur au Lac', 'Signature Loft', 473, 2, 'true'),
('858', 'Park Hyatt Zurich', 'Signature Loft', 461, 2, 'true'),
('202', 'Park Hyatt Zurich', 'Premier Residence', 2208, 4, 'false'),
('613', 'Park Hyatt Zurich', 'Executive Suite', 765, 3, 'true'),
('525', 'ibis Zurich City West', 'Ocean Queen Room', 186, 2, 'true'),
('149', 'ibis Zurich City West', 'Elite Loft', 564, 2, 'true'),
('659', 'The Ritz-Carlton Philadelphia', 'Premier King Room', 833, 2, 'true'),
('811', 'The Ritz-Carlton Philadelphia', 'Elite Studio', 1330, 2, 'false'),
('903', 'Loews Philadelphia Hotel', 'Deluxe Residence', 455, 2, 'false'),
('556', 'Club Quarters Philadelphia', 'Signature Corner Suite', 432, 2, 'true'),
('910', 'Jinling Hotel Nanjing', 'Royal Suite', 249, 2, 'false'),
('154', 'Shangri-La Nanjing', 'City Studio', 640, 2, 'true'),
('570', 'Shangri-La Nanjing', 'Garden Corner Suite', 387, 2, 'true'),
('436', 'Shangri-La Nanjing', 'Royal Queen Room', 617, 3, 'true'),
('128', 'Holiday Inn Nanjing Aqua City', 'Garden Suite', 308, 2, 'false'),
('430', 'Holiday Inn Nanjing Aqua City', 'Elite Residence', 233, 2, 'true'),
('577', 'The St. Regis Osaka', 'Premier Suite', 1720, 4, 'true'),
('540', 'The St. Regis Osaka', 'Elite Loft', 2777, 4, 'false'),
('239', 'The St. Regis Osaka', 'Executive King Room', 696, 2, 'true'),
('547', 'Conrad Osaka', 'Garden Suite', 637, 4, 'true'),
('522', 'Conrad Osaka', 'City King Room', 467, 4, 'true'),
('671', 'Hotel Keihan Yodoyabashi', 'Club Family Suite', 190, 2, 'true'),
('437', 'Hyatt Ziva Cancun', 'Executive Suite', 471, 2, 'false'),
('653', 'Hyatt Ziva Cancun', 'Grand Loft', 508, 2, 'true'),
('572', 'Secrets The Vine Cancun', 'Grand Residence', 513, 2, 'true'),
('188', 'Secrets The Vine Cancun', 'Executive Suite', 315, 4, 'false'),
('797', 'Krystal Cancun', 'Skyline Suite', 244, 3, 'false'),
('416', 'Krystal Cancun', 'City Queen Room', 308, 4, 'false'),
('479', 'Wanda Vista Changsha', 'City Studio', 554, 2, 'true'),
('988', 'Sheraton Changsha Hotel', 'Elite Family Suite', 638, 2, 'true'),
('869', 'Sheraton Changsha Hotel', 'Elite Studio', 397, 4, 'false'),
('495', 'Holiday Villa Changsha City Centre', 'Ocean Suite', 496, 2, 'false'),
('700', 'Shangri-La Wuhan', 'Executive Penthouse', 596, 4, 'true'),
('153', 'Shangri-La Wuhan', 'Panorama Studio', 459, 2, 'true'),
('437', 'Wuhan Marriott Hotel Optics Valley', 'Royal King Room', 445, 2, 'true'),
('463', 'Holiday Inn Wuhan Riverside', 'Royal King Room', 632, 4, 'false'),
('962', 'Holiday Inn Wuhan Riverside', 'Signature Junior Suite', 378, 2, 'false'),
('467', 'NH Collection Copenhagen', 'Panorama Corner Suite', 507, 2, 'true'),
('663', 'NH Collection Copenhagen', 'Grand Corner Suite', 228, 2, 'false'),
('677', 'Copenhagen Marriott Hotel', 'Elite Queen Room', 385, 2, 'false'),
('842', 'Copenhagen Marriott Hotel', 'Premier Loft', 179, 2, 'false'),
('709', 'Wakeup Copenhagen', 'Garden Penthouse', 75, 4, 'true'),
('122', 'Grand Hyatt Jeju', 'Elite Penthouse', 282, 2, 'true'),
('515', 'Grand Hyatt Jeju', 'Panorama Penthouse', 646, 4, 'true'),
('236', 'Jeju Sun Hotel', 'Executive King Room', 166, 2, 'true'),
('272', 'Jeju Sun Hotel', 'Deluxe Studio', 264, 2, 'true'),
('286', 'Ramada Plaza Jeju', 'Club Suite', 377, 2, 'false'),
('475', 'Ramada Plaza Jeju', 'Deluxe Family Suite', 208, 4, 'true'),
('377', 'Ramada Plaza Jeju', 'Signature Queen Room', 422, 2, 'true'),
('991', 'Taj Krishna Hyderabad', 'Deluxe Studio', 153, 4, 'true'),
('444', 'Taj Krishna Hyderabad', 'City King Room', 380, 4, 'false'),
('139', 'ITC Kohenur Hyderabad', 'City King Room', 359, 2, 'true'),
('206', 'Lemon Tree Premier Hitec City', 'Signature Residence', 414, 3, 'true'),
('791', 'Emirates Palace Mandarin Oriental', 'Elite Penthouse', 481, 2, 'false'),
('581', 'Emirates Palace Mandarin Oriental', 'Executive Penthouse', 1065, 4, 'false'),
('863', 'Emirates Palace Mandarin Oriental', 'Ocean Loft', 2315, 2, 'false'),
('677', 'Hilton Abu Dhabi Yas Island', 'Royal Penthouse', 254, 2, 'true'),
('792', 'Hilton Abu Dhabi Yas Island', 'Garden Suite', 561, 2, 'true'),
('147', 'Southern Sun Abu Dhabi', 'City Penthouse', 333, 2, 'true'),
('672', 'Southern Sun Abu Dhabi', 'Elite Queen Room', 422, 2, 'true'),
('500', 'Marriott Mena House', 'Signature Junior Suite', 413, 2, 'true'),
('486', 'Marriott Mena House', 'Ocean Family Suite', 611, 3, 'false'),
('193', 'Marriott Mena House', 'Deluxe Penthouse', 418, 2, 'false'),
('426', 'Four Seasons Cairo at Nile Plaza', 'Executive Loft', 597, 3, 'false'),
('754', 'Four Seasons Cairo at Nile Plaza', 'Garden Residence', 1291, 2, 'true'),
('194', 'Four Seasons Cairo at Nile Plaza', 'Executive Corner Suite', 1329, 3, 'true'),
('639', 'Steigenberger Hotel El Tahrir', 'Garden Residence', 265, 2, 'true'),
('911', 'Steigenberger Hotel El Tahrir', 'Garden Queen Room', 254, 4, 'true'),
('341', 'JW Marriott Zhengzhou', 'Deluxe Suite', 417, 4, 'false'),
('783', 'JW Marriott Zhengzhou', 'Royal Penthouse', 465, 3, 'false'),
('827', 'Hilton Zhengzhou', 'Skyline Corner Suite', 639, 2, 'false'),
('115', 'Hilton Zhengzhou', 'Premier King Room', 269, 2, 'true'),
('154', 'Holiday Inn Zhengzhou', 'Deluxe King Room', 413, 4, 'true'),
('858', 'Armani Hotel Milano', 'Grand Corner Suite', 341, 3, 'false'),
('624', 'Excelsior Hotel Gallia', 'Skyline Junior Suite', 567, 4, 'false'),
('501', 'Excelsior Hotel Gallia', 'Elite Corner Suite', 228, 2, 'false'),
('963', 'Excelsior Hotel Gallia', 'Elite Residence', 430, 2, 'false'),
('416', 'Hotel Berna', 'Ocean Studio', 561, 2, 'false'),
('800', 'Grand America Hotel', 'Deluxe Penthouse', 601, 4, 'false'),
('220', 'Grand America Hotel', 'Garden King Room', 518, 2, 'true'),
('940', 'Grand America Hotel', 'Club Suite', 601, 3, 'false'),
('749', 'Little America Hotel', 'Premier Residence', 256, 2, 'true'),
('110', 'Metropolitan Inn', 'Royal Corner Suite', 195, 2, 'false'),
('195', 'Swiss Grand Xiamen', 'City Residence', 543, 2, 'true'),
('460', 'Swiss Grand Xiamen', 'Royal Junior Suite', 541, 2, 'true'),
('148', 'Langham Place Xiamen', 'Executive Junior Suite', 934, 2, 'true'),
('877', 'Langham Place Xiamen', 'Executive Queen Room', 2263, 2, 'true'),
('742', 'Ibis Xiamen Kaiyuan', 'Royal Loft', 135, 2, 'false'),
('801', 'Washington Dulles Airport Marriott', 'Royal Junior Suite', 328, 4, 'false'),
('273', 'Hilton Washington Dulles Airport', 'Grand Corner Suite', 281, 4, 'false'),
('207', 'Hyatt Place Dulles Airport', 'Royal Loft', 550, 2, 'false'),
('261', 'Sagamore Pendry Baltimore', 'Panorama Residence', 374, 3, 'true'),
('109', 'Sagamore Pendry Baltimore', 'Grand Corner Suite', 523, 2, 'false'),
('149', 'Hyatt Regency Baltimore', 'Elite Penthouse', 421, 4, 'true'),
('312', 'Hyatt Regency Baltimore', 'Club Queen Room', 483, 2, 'true'),
('145', 'Lord Baltimore Hotel', 'Royal Junior Suite', 539, 4, 'true'),
('207', 'Hotel Okura Fukuoka', 'Panorama Studio', 294, 2, 'false'),
('702', 'Hotel Okura Fukuoka', 'Garden Junior Suite', 494, 3, 'false'),
('841', 'Grand Hyatt Fukuoka', 'Royal Junior Suite', 507, 2, 'true'),
('770', 'Grand Hyatt Fukuoka', 'Heritage Studio', 453, 2, 'false'),
('604', 'The B Hakata', 'Skyline Penthouse', 298, 3, 'false'),
('808', 'The B Hakata', 'Garden Studio', 437, 3, 'false'),
('839', 'Hilton Urumqi', 'Deluxe Penthouse', 444, 2, 'true'),
('668', 'Universal Hotel Urumqi', 'Club Loft', 510, 2, 'false'),
('130', 'Universal Hotel Urumqi', 'Elite Queen Room', 416, 4, 'false'),
('643', 'Jinjiang Inn Urumqi', 'Skyline Loft', 110, 2, 'true'),
('924', 'The Hay-Adams', 'Garden Family Suite', 501, 4, 'false'),
('236', 'The Hay-Adams', 'Elite King Room', 638, 2, 'false'),
('397', 'Willard InterContinental', 'Royal King Room', 488, 2, 'true'),
('291', 'Willard InterContinental', 'City Family Suite', 453, 2, 'false'),
('430', 'Washington Plaza Hotel', 'City Junior Suite', 251, 2, 'true'),
('602', 'Washington Plaza Hotel', 'Club Residence', 506, 3, 'true'),
('742', 'Shangri-La Qingdao', 'Club Penthouse', 596, 4, 'true'),
('837', 'Shangri-La Qingdao', 'Ocean Penthouse', 277, 3, 'true'),
('749', 'Shangri-La Qingdao', 'Premier Residence', 522, 4, 'true'),
('162', 'The Westin Qingdao', 'Executive Studio', 305, 2, 'true'),
('920', 'The Westin Qingdao', 'Club Corner Suite', 572, 3, 'true'),
('264', 'Holiday Inn Qingdao City Centre', 'Executive Queen Room', 464, 2, 'false');