DROP DATABASE IF EXISTS DBVOLI;
CREATE DATABASE DBVOLI;
USE DBVOLI;

---------------------------
-- TABELLA AEROPORTI
---------------------------
CREATE TABLE AEROPORTO(
 iata VARCHAR(3) PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 continente VARCHAR(50) NOT NULL,
 stato VARCHAR(80) NOT NULL,
 citta VARCHAR(80) NOT NULL,
 passeggeri DECIMAL(5,1) NOT NULL,
 corsie INT NOT NULL
);

---------------------------
-- TABELLA COMPAGNIE AEREE
---------------------------
CREATE TABLE COMPAGNIA(
    nome VARCHAR(100) PRIMARY KEY,
    main_hub VARCHAR(3) NOT NULL,
    CONSTRAINT fk_hub_compagnia 
		FOREIGN KEY (main_hub)
        REFERENCES AEROPORTO(iata)
);

---------------------------
-- DB ROTTE
---------------------------
 CREATE TABLE ROTTA(
	id INT AUTO_INCREMENT PRIMARY KEY,
    iata_partenza VARCHAR(3) NOT NULL,
    iata_arrivo VARCHAR(3) NOT NULL,
    compagnia VARCHAR(30) NOT NULL,
    CONSTRAINT fk_partenza
		FOREIGN KEY (iata_partenza)
        REFERENCES AEROPORTO(iata),
	CONSTRAINT fk_arrivo
		FOREIGN KEY (iata_arrivo)
        REFERENCES AEROPORTO(iata),
	CONSTRAINT fk_compagnia
		FOREIGN KEY (compagnia)
        REFERENCES COMPAGNIA(nome)
);

---------------------------
-- DB VOLI
---------------------------
CREATE TABLE VOLO(
	id INT AUTO_INCREMENT PRIMARY KEY,
    rotta INT NOT NULL,
    modello_aereo VARCHAR(30) NOT NULL,
    timestamp DATETIME NOT NULL,
    
    CONSTRAINT fk_rotta
		FOREIGN KEY (rotta)
        REFERENCES ROTTA(id)
);

-------------------------
-- INSERIMENTO AEROPORTI
-------------------------
INSERT INTO AEROPORTO(iata, nome, continente, stato, citta, passeggeri, corsie)
VALUES
('ATL', 'Hartsfield Jackson Atlanta International Airport', 'NA', 'Stati Uniti', 'Atlanta', 108.1, 5),
('DXB', 'Dubai International Airport', 'AS', 'Emirati Arabi Uniti', 'Dubai', 92.3, 2),
('DFW', 'Dallas Fort Worth International Airport', 'NA', 'Stati Uniti', 'Dallas', 87.8, 7),
('HND', 'Tokyo Haneda International Airport', 'AS', 'Giappone', 'Tokyo', 85, 4),
('LHR','London Heathrow Airport','EU','Regno Unito','Londra', 83.9, 2),
('DEN','Denver International Airport','NA','Stati Uniti','Denver', 82.4, 6),
('IST','İstanbul Airport','EU','Turchia','Istanbul', 80.1, 5),
('ORD','Chicago O Hare International Airport','NA','Stati Uniti','Chicago', 80, 8),
('DEL','Indira Gandhi International Airport','AS','India','Nuova Delhi', 77.8, 4),
('PVG','Shanghai Pudong International Airport','AS','Cina','Shanghai', 76.8, 5),
('LAX','Los Angeles International Airport','NA','Stati Uniti','Los Angeles', 76.6, 4),
('CAN','Guangzhou Baiyun International Airport','AS','Cina','Guangzhou', 76.4, 5),
('ICN','Incheon International Airport','AS','Corea del Sud','Seoul', 71.2, 4),
('CDG','Charles de Gaulle International Airport','EU','Francia','Parigi', 70.3, 4),
('SIN','Singapore Changi Airport','AS','Singapore','Singapore', 67.7, 2),
('PEK','Beijing Capital International Airport','AS','Cina','Beijing', 67.4, 3),
('AMS','Amsterdam Airport Schiphol','EU','Paesi Bassi','Amsterdam', 66.8, 6),
('MAD','Adolfo Suárez Madrid–Barajas Airport','EU','Spagna','Madrid', 66.2, 4),
('JFK','John F Kennedy International Airport','NA','Stati Uniti','New York', 63.3, 4),
('BKK','Suvarnabhumi Airport','AS','Thailandia','Bangkok', 62.2, 3),
('FRA','Frankfurt Airport','EU','Germania','Francoforte', 61.6, 4),
('SZX','Shenzhen Bao an International Airport','AS','Cina','Shenzhen', 61.5, 3),
('CLT','Charlotte Douglas International Airport','NA','Stati Uniti','Charlotte', 58.8, 3),
('LAS','Harry Reid International Airport','NA','Stati Uniti','Las Vegas', 58.4, 4),
('MCO','Orlando International Airport','NA','Stati Uniti','Orlando', 57.2, 4),
('KUL','Kuala Lumpur International Airport','AS','Malesia','Kuala Lumpur', 57.1, 3),
('MIA','Miami International Airport','NA','Stati Uniti','Miami', 56, 4),
('BOM','Chhatrapati Shivaji International Airport','AS','India','Mumbai', 55.1, 2),
('BCN','Josep Tarradellas Barcelona-El Prat Airport','EU','Spagna','Barcellona', 55, 3),
('TFU','Chengdu Tianfu International Airport','AS','Cina','Chengdu', 54.9, 3),
('HKG','Hong Kong International Airport','AS','Hong Kong','Hong Kong', 53.1, 3),
('SEA','Seattle-Tacoma International Airport','NA','Stati Uniti','Seattle', 52.6, 3),
('DOH','Hamad International Airport','AS','Qatar','Doha', 52.5, 2),
('PHX','Phoenix Sky Harbor International Airport','NA','Stati Uniti','Phoenix', 52.3, 3),
('SFO','San Francisco International Airport','NA','Stati Uniti','San Francisco', 52.3, 4),
('MNL','Ninoy Aquino International Airport','AS','Filippine','Manila', 50.1, 2),
('PKX','Beijing Daxing International Airport','AS','Cina','Beijing', 49.4, 4),
('FCO','Rome-Fiumicino Leonardo Da Vinci Airport','EU','Italia','Roma', 49.2, 3),
('TPE','Taiwan Taoyuan International Airport','AS','Taiwan','Taipei', 49.1, 2),
('JED','King Abdulaziz International Airport','AS','Arabia Saudita','Jeddah', 48.9, 3),
('EWR','Newark Liberty International Airport','NA','Stati Uniti','Newark', 48.7, 3),
('CKG','Chongqing Jiangbei International Airport','AS','Cina','Chongqing', 48.5, 4),
('IAH','George Bush Intercontinental Houston Airport','NA','Stati Uniti','Houston', 48.1, 5),
('HGH','Hangzhou Xiaoshan International Airport','AS','Cina','Hangzhou', 48.1, 2),
('SHA','Shanghai Hongqiao International Airport','AS','Cina','Shanghai', 48, 2),
('KMG','Kunming Changshui International Airport','AS','Cina','Kunming', 47, 2),
('XIY','Xi an Xianyang International Airport','AS','Cina','Xianyang', 47, 4),
('YYZ','Toronto Lester B. Pearson International Airport','NA','Canada','Toronto', 46.8, 5),
('BOG','El Dorado International Airport','SA','Colombia','Bogota', 45.8, 2),
('MEX','Benito Juarez International Airport','NA','Messico','Città del Messico', 45.4, 2),
('BOS','Logan International Airport','NA','Stati Uniti','Boston', 43.5, 6),
('LGW','London Gatwick Airport','EU','Regno Unito','Londra', 43.2, 2),
('GRU','Guarulhos - Governador André Franco Montoro International Airport','SA','Brasile','San Paolo', 43, 2),
('SVO','Sheremetyevo International Airport','EU','Russia','Mosca', 43, 3),
('BLR','Kempegowda International Airport Bengaluru','AS','India','Bangaluru', 41.9, 2),
('MUC','Munich Airport','EU','Germania','Monaco', 41.6, 2),
('SAW','Istanbul Sabiha Gökçen International Airport','EU','Turchia','Istanbul', 41.4, 2),
('SYD','Sydney Kingsford Smith International Airport','OCE','Australia','Sydney', 41.4, 3),
('SGN','Tan Son Nhat International Airport','AS','Vietnam','Ho Chi Minh', 40, 2),
('NRT','Narita International Airport','AS','Giappone','Narita', 39.8, 2),
('AYT','Antalya International Airport','EU','Turchia','Antalya', 38.3, 3),
('DUB','Dublin Airport','EU','Irlanda','Dublino', 37.7, 3),
('MSP','Minneapolis–Saint Paul International Airport','NA','Stati Uniti','Minneapolis', 37, 4),
('RUH','King Khalid International Airport','AS','Arabia Saudita','Riyadh', 37, 2),
('FLL','Fort Lauderdale Hollywood International Airport','NA','Stati Uniti','Fort Lauderdale', 35.2, 2),
('MEL','Melbourne Airport','OCE','Australia','Melbourne', 35.1, 2),
('CGK','Soekarno-Hatta International Airport','AS','Indonesia','Jakarta', 35, 3),
('LIS','Lisbon Humberto Delgado Airport','EU','Portogallo','Lisbon', 35, 1),
('LGA','LaGuardia Airport','NA','Stati Uniti','New York', 33.5, 2),
('PMI','Palma de Mallorca Airport','EU','Spagna','Palma di Maiorca', 33.3, 2),
('ORY','Paris-Orly Airport','EU','Francia','Parigi', 33.1, 3),
('DTW','Detroit Metropolitan Wayne County Airport','NA','Stati Uniti','Detroit', 33, 6),
('HAN','Noi Bai International Airport','AS','Vietnam','Hanoi', 32.5, 2),
('MAN','Manchester Airport','EU','Regno Unito','Manchester', 32.1, 2),
('ATH','Athens Eleftherios Venizelos International Airport','EU','Grecia','Atene', 31.9, 2),
('VIE','Vienna International Airport','EU','Austria','Vienna', 31.7, 2),
('ZRH','Zürich Airport','EU','Svizzera','Zurigo', 31.2, 3),
('PHL','Philadelphia International Airport','NA','Stati Uniti','Philadelphia', 30.9, 4),
('NKG','Nanjing Lukou International Airport','AS','Cina','Nanjing', 30.7, 2),
('KIX','Kansai International Airport','AS','Giappone','Osaka', 30.6, 2),
('CUN','Cancún International Airport','NA','Messico','Cancùn', 30.4, 2),
('CSX','Changsha Huanghua International Airport','AS','Cina','Changsha', 30.3, 2),
('DMK','Don Mueang International Airport','AS','Thailandia','Bangkok', 30, 2),
('WUH','Wuhan Tianhe International Airport','AS','Cina','Wuhan', 30, 3),
('CPH','Copenhagen Kastrup Airport','EU','Danimarca','Copenhagen', 29.9, 3),
('STN','London Stansted Airport','EU','Regno Unito','Londra', 29.8, 1),
('CJU','Jeju International Airport','AS','Corea del Sud','Jeju', 29.6, 2),
('HYD','Rajiv Gandhi International Airport','AS','India','Hyderabad', 29, 2),
('AUH','Zayed International Airport','AS','Emirati Arabi Uniti','Abu Dhabi', 28.8, 2),
('CAI','Cairo International Airport','AFR','Egitto','Il Cairo', 28.8, 3),
('CGO','Zhengzhou Xinzheng International Airport','AS','Cina','Zhengzhou', 28.5, 2),
('MXP','Milan Malpensa International Airport','EU','Italia','Milano', 28.5, 2),
('SLC','Salt Lake City International Airport','NA','Stati Uniti','Salt Lake City', 28.4, 4),
('XMN','Xiamen Gaoqi International Airport','AS','Cina','Xiamen', 27.7, 1),
('IAD','Washington Dulles International Airport','NA','Stati Uniti','Dulles', 27.3, 4),
('BWI','Baltimore Washington International Thurgood Marshall Airport','NA','Stati Uniti','Baltimore', 27.1, 3),
('FUK','Fukuoka Airport','AS','Giappone','Fukuoka', 26.7, 2),
('URC','Ürümqi Tianshan International Airport','AS','Cina','Ürümqi', 26.4, 3),
('DCA','Ronald Reagan Washington National Airport','NA','Stati Uniti','Washington', 26.3, 3),
('TAO','Qingdao Jiaodong International Airport','AS','Cina','Qingdao', 26.2, 2);


-------------------------
-- INSERIMENTO COMPAGNIA
-------------------------
INSERT INTO COMPAGNIA(nome, main_hub)
VALUES
('Ryanair', 'STN'),
('KLM Royal Dutch Airlines','AMS'),
('Vueling Airlines','BCN'),
('easyJet','LGW'),
('SkyWest','DEN'),
('Southwest','PHX'),
('Delta Airlines','ATL'),
('Iberia','MAD'),
('American Airlines','DFW'),
('United','EWR'),
('Turkish Airlines','IST'),
('indiGO','DEL'),
('Scandinavian Airlines System','CPH'),
('China Eastern Airlines','PVG'),
('Lufthansa','FRA'),
('Envoy Airlines','DFW'),
('Transavia Airlines','AMS'),
('China Southern Airlines','CAN'),
('Wizz Air Malta','MXP'),
('Air China','PEK'),
('Emirates','DXB'),
('Jet2','MAN'),
('Air France','CDG'),
('PSA Airlines','CLT'),
('Air Europa','MAD'),
('Avianca','BOG'),
('Pegasus Airlines','SAW'),
('JetBlue','JFK'),
('Endeavor Air','MSP'),
('Allegiant Air','LAS'),
('Volotea','BCN'),
('Qatar Airways','DOH'),
('British Airways','LHR'),
('FlyDubai','DXB'),
('Republic Airways','ORD'),
('Cathay Pacific','HKG'),
('Piedmont Airways','PHL'),
('AirAsia','KUL'),
('Latam Brasil','GRU'),
('ITA Airways','FCO'),
('Lauda Europe','PMI'),
('Alaska Airlines','SEA'),
('China Express Airlines','CKG'),
('Saudia','RUH'),
('Sichuan Airlines','TFU'),	
('Cape Air','BOS'),
('Condor Flugdienst','FRA'),
('Aegean Airlines','ATH'),
('AeroMéxico','MEX'),
('Air Canada','YYZ'),
('Virgin Airlines','MEL'),
('Japan Airlines','NRT'),
('Qantas', 'SYD'),
('Singapore Airlines','SIN'),
('Etihad Airways','AUH'),
('Korean Air', 'ICN'),
('Aeroflot', 'SVO'),
('Vietnam Airlines','SGN'),
('Air India', 'DEL');
-------------------------
-- INSERIMENTO ROTTE
-------------------------
INSERT INTO ROTTA(iata_partenza, iata_arrivo, compagnia)
VALUES
('ATL','AMS','KLM Royal Dutch Airlines'),
('ATL','BCN','Delta Airlines'),
('ATL','DTW','Delta Airlines'),
('ATL','LGA','American Airlines'),
('ATL','JFK','United'),
('DXB','RUH','FlyDubai'),
('DXB','FRA','Emirates'),
('DXB','DEL','Air India'),
('DXB','HKG','Emirates'),
('DXB','JFK','Emirates'),
('DFW','PVG','American Airlines'),	
('DFW','LHR','British Airways'),
('DFW','DOH','Qatar Airways'),
('DFW','MIA','Delta Airlines'),
('DFW','ORD','United'),
('HND','HKG','Cathay Pacific'),
('HND','JFK','Japan Airlines'),
('HND','FCO','ITA Airways'),
('HND','DXB','Emirates'),
('HND','NRT','Japan Airlines'),
('LHR','AMS','KLM Royal Dutch Airlines'),
('LHR','CDG', 'Air France'),
('LHR','FRA','Lufthansa'),
('LHR','TFU','Air China'),
('LHR','LAX','British Airways'),
('DEN','ORD','United'),
('DEN','CDG','Air France'),
('DEN','PHX','American Airlines'),
('DEN','IAH','Southwest'),
('DEN','SEA','Alaska Airlines'),
('IST','BCN','Turkish Airlines'),
('IST','CAI','Turkish Airlines'),
('IST','FRA','Lufthansa'),
('IST','CAN','China Southern Airlines'),
('IST','MIA','Turkish Airlines'),
('ORD','LGA','United'),
('ORD','PHL','American Airlines'),
('ORD','CLT','Republic Airways'),
('ORD','CAN','Air China'),
('ORD','LHR','British Airways'),
('DEL','DXB','Air India'),
('DEL','BOM','IndiGO'),
('DEL','HKG','Cathay Pacific'),
('DEL','HYD','Air India'),
('DEL','JFK','Air India'),
('PVG','HND','China Eastern Airlines'),
('PVG','CAN','China Southern Airlines'),
('PVG','AUH','Etihad Airways'),
('PVG','MXP','China Eastern Airlines'),
('PVG','LAX','Air China'),
('LAX','DFW','United'),
('LAX','SEA','Delta Airlines'),
('LAX','JFK','American Airlines'),
('LAX','SZX','Air China'),
('LAX','MAD','Iberia'),
('CAN','PKX','China Southern Airlines'),
('CAN','SHA','China Southern Airlines'),
('CAN','LHR','Air China'),
('CAN','SFO','China Southern Airlines'),
('CAN','FRA','China Southern Airlines'),
('ICN','HKG','Cathay Pacific'),
('ICN','HND','Korean Air'),
('ICN','JFK','Korean Air'),
('ICN','AMS','KLM Royal Dutch Airlines'),
('ICN','LAX','Korean Air'),
('CDG','BCN','Iberia'),
('CDG','MUC','Lufthansa'),
('CDG','CPH','Scandinavian Airlines System'),
('CDG','DXB','Emirates'),
('CDG','JFK','Air France'),
('SIN','HKG','Cathay Pacific'),
('SIN','HND','Singapore Airlines'),
('SIN','JFK','Singapore Airlines'),
('SIN','AMS','KLM Royal Dutch Airlines'),
('SIN','LAX','American Airlines'),
('PEK','HND','Air China'),
('PEK','CDG','Air France'),
('PEK','SFO','Air China'),
('PEK','SHA','Air China'),
('PEK','LHR','British Airways'),
('AMS','BCN','Vueling Airlines'),
('AMS','FRA','KLM Royal Dutch Airlines'),
('AMS','JFK','KLM Royal Dutch Airlines'),
('AMS','LGA','KLM Royal Dutch Airlines'),
('AMS','LHR','KLM Royal Dutch Airlines'),
('MAD','BCN','Iberia'),
('MAD','PMI','Ryanair'),
('MAD','BOG','Avianca'),
('MAD','JFK','Iberia'),
('MAD','IST','Turkish Airlines'),
('JFK','LAX','American Airlines'),
('JFK','MIA','American Airlines'),
('JFK','LHR','British Airways'),
('JFK','ATL','Delta Airlines'),
('JFK','HKG','Cathay Pacific'),
('BKK','HKG','Singapore Airlines'),
('BKK','TPE','Air China'),
('BKK','KUL','Singapore Airlines'),
('BKK','JED','Saudia'),
('BKK','ICN','Korean Air'),
('FRA','PVG','China Eastern Airlines'),
('FRA','IST','Lufthansa'),
('FRA','HND','Japan Airlines'),
('FRA','JFK','Air France'),
('FRA','AMS','KLM Royal Dutch Airlines'),
('SZX','PEK','China Eastern Airlines'),
('SZX','HGH','China Southern Airlines'),
('SZX','TFU','China Southern Airlines'),
('SZX','IST','Turkish Airlines'),
('SZX','LAX','Air China'),
('CLT','ATL','American Airlines'),
('CLT','MIA','Piedmont Airways'),
('CLT','DFW','PSA Airlines'),
('CLT','MAD','American Airlines'),
('CLT','BOS','PSA Airlines'),
('LAS','LAX','Delta Airlines'),
('LAS','DEN','Southwest'),
('LAS','PHX','Southwest'),
('LAS','YYZ','Air Canada'),
('LAS','AMS','KLM Royal Dutch Airlines'),
('MCO','ATL','Southwest'),
('MCO','DFW','Southwest'),
('MCO','EWR','JetBlue'),
('MCO','MAN','Virgin Airlines'),
('MCO','DXB','Emirates'),
('KUL','SIN','Singapore Airlines'),
('KUL','HKG','Cathay Pacific'),
('KUL','CAN','China Southern Airlines'),
('KUL','SYD','Qantas'),
('KUL','IST','Turkish Airlines'),
('MIA','BOG','Avianca'),
('MIA','MAD','Iberia'),
('MIA','ATL','Delta Airlines'),
('MIA','DFW','Delta Airlines'),
('MIA','IAH','Southwest'),
('BOM','BLR','IndiGO'),
('BOM','HYD','IndiGO'),
('BOM','DEL','IndiGO'),
('BOM','DXB','Emirates'),
('BOM','BLR','Air India'),
('BCN','MAD','Iberia'),
('BCN','PMI','Ryanair'),
('BCN','MXP','easyJet'),
('BCN','LGW','Vueling Airlines'),
('BCN','JFK','Iberia'),
('TFU','CAN','China Eastern Airlines'),
('TFU','PVG','China Southern Airlines'),
('TFU','URC','Air China'),
('TFU','FCO','Air China'),
('TFU','MAD','Air China'),
('HKG','TPE','Cathay Pacific'),
('HKG','NRT','Air China'),
('HKG','KIX','Air China'),
('HKG','SYD','Cathay Pacific'),
('HKG','LAX','Cathay Pacific'),
('SEA','DEN','Alaska Airlines'),
('SEA','PHX','Alaska Airlines'),
('SEA','LAX','Alaska Airlines'),
('SEA','YYZ','Alaska Airlines'),
('SEA','AMS','KLM Royal Dutch Airlines'),
('DOH','DXB','Qatar Airways'),
('DOH','BCN','Qatar Airways'),
('DOH','AMS','Qatar Airways'),
('DOH','LHR','Qatar Airways'),
('DOH','JFK','Qatar Airways'),
('PHX','LAX','Southwest'),
('PHX','DEN','Southwest'),
('PHX','DFW','SkyWest'),
('PHX','SEA','American Airlines'),
('PHX','ORD','American Airlines'),
('SFO','LAX','SkyWest'),
('SFO','LAS','United'),
('SFO','DEN','United'),
('SFO','CDG','Air France'),
('SFO','PEK','Delta Airlines'),
('MNL','HND','Cathay Pacific'),
('MNL','HKG','Cathay Pacific'),
('MNL','SIN','Singapore Airlines'),
('MNL','JFK','Singapore Airlines'),
('MNL','LHR','Singapore Airlines'),
('PKX','SZX','China Southern Airlines'),
('PKX','HKG','China Southern Airlines'),
('PKX','XIY','China Eastern Airlines'),
('PKX','IST','Turkish Airlines'),
('PKX','FRA','Air China'),
('FCO','MAD','Wizz Air Malta'),
('FCO','MXP','Wizz Air Malta'),
('FCO','PVG','ITA Airways'),
('FCO','JFK','ITA Airways'),
('FCO','PMI','Ryanair'),
('TPE','HKG','Air China'),
('TPE','BKK','Singapore Airlines'),
('TPE','NRT','Japan Airlines'),
('TPE','SIN','Singapore Airlines'),
('TPE','LAX','Air China'),
('JED','RUH','Saudia'),
('JED','CAI','Saudia'),
('JED','DXB','Saudia'),
('JED','IST','Turkish Airlines'),
('JED','AMS','KLM Royal Dutch Airlines'),
('EWR','MAD','United'),
('EWR','ATL','United'),
('EWR','MCO','United'),
('EWR','IAH','Republic Airways'),
('EWR','PMI','United'),
('CKG','SZX','China Southern Airlines'),
('CKG','NKG','China Eastern Airlines'),
('CKG','PVG','China Southern Airlines'),
('CKG','FCO','ITA Airways'),
('CKG','SIN','Singapore Airlines'),
('IAH','ORD','SkyWest'),
('IAH','ATL','United'),
('IAH','DFW','United'),
('IAH','AMS','United'),
('IAH','CUN','United'),
('HGH','SZX','Air China'),
('HGH','CAN','Air China'),
('HGH','PEK','China Southern Airlines'),
('HGH','KMG','China Southern Airlines'),
('HGH','MXP','ITA Airways'),
('SHA','SZX','China Eastern Airlines'),
('SHA','CAN','China Eastern Airlines'),
('SHA','XIY','China Eastern Airlines'),
('SHA','PEK','Air China'),
('SHA','XMN','China Eastern Airlines'),
('KMG','XIY','China Eastern Airlines'),
('KMG','CGO','China Southern Airlines'),
('KMG','CAN','China Southern Airlines'),
('KMG','KUL','Air China'),
('KMG','SHA','China Eastern Airlines'),
('XIY','KMG','China Eastern Airlines'),
('XIY','SZX','China Southern Airlines'),
('XIY','SHA','China Eastern Airlines'),
('XIY','CAN','China Southern Airlines'),
('XIY','MXP','ITA Airways'),
('YYZ','LHR','British Airways'),
('YYZ','AMS','KLM Royal Dutch Airlines'),
('YYZ','JFK','Air Canada'),
('YYZ','CDG','Air Canada'),
('YYZ','FRA','Air Canada'),
('BOG','MAD','Avianca'),
('BOG','BCN','Avianca'),
('BOG','JFK','Avianca'),
('BOG','IST','Turkish Airlines'),
('BOG','AMS','KLM Royal Dutch Airlines'),
('MEX','MAD','AeroMéxico'),
('MEX','BCN','AeroMéxico'),
('MEX','JFK','AeroMéxico'),
('MEX','IST','Turkish Airlines'),
('MEX','AMS','KLM Royal Dutch Airlines'),
('BOS','JFK','JetBlue'),
('BOS','LGA','JetBlue'),
('BOS','LHR','British Airways'),
('BOS','CDG','Air France'),
('BOS','AMS','KLM Royal Dutch Airlines'),
('LGW','BCN','easyJet'),
('LGW','PMI','easyJet'),
('LGW','MAD','easyJet'),
('LGW','ATH','Ryanair'),
('LGW','AMS','Vueling Airlines'),
('GRU','MAD','Latam Brasil'),
('GRU','AMS','Latam Brasil'),
('GRU','BCN','Latam Brasil'),
('GRU','BOG','Latam Brasil'),
('GRU','MCO','United'),
('SVO','IST','Turkish Airlines'),
('SVO','AYT','Turkish Airlines'),
('SVO','PKX','China Eastern Airlines'),
('SVO','AUH','Etihad Airways'),
('SVO','DXB','Aeroflot'),
('BLR','DEL','IndiGO'),
('BLR','DXB','Emirates'),
('BLR','BOM','IndiGO'),
('BLR','HYD','IndiGO'),
('BLR','LHR','Air India'),
('MUC','MAD','Lufthansa'),
('MUC','PMI','easyJet'),
('MUC','FRA','Lufthansa'),
('MUC','PEK','Lufthansa'),
('MUC','ATL','Lufthansa'),
('SAW','AMS','Pegasus Airlines'),
('SAW','AYT','Pegasus Airlines'),
('SAW','DXB','Pegasus Airlines'),
('SAW','JED','Pegasus Airlines'),
('SAW','MAD','Pegasus Airlines'),
('SYD','MEL','Qantas'),
('SYD','DXB','Qantas'),
('SYD','KUL','Qantas'),
('SYD','HND','Virgin Airlines'),
('SYD','TFU','Qantas'),
('SGN','HAN','Vietnam Airlines'),
('SGN','HKG','Vietnam Airlines'),
('SGN','SIN','Singapore Airlines'),
('SGN','TPE','Vietnam Airlines'),
('SGN','CDG','Air France'),
('NRT','HKG','Cathay Pacific'),
('NRT','ICN','Korean Air'),
('NRT','PVG','Air China'),
('NRT','LAX','Japan Airlines'),
('NRT','JFK','Japan Airlines'),
('AYT','IST','Pegasus Airlines'),
('AYT','DXB','Pegasus Airlines'),
('AYT','AMS','Turkish Airlines'),
('AYT','JED','Pegasus Airlines'),
('AYT','LHR','Turkish Airlines'),
('DUB','LHR','Ryanair'),
('DUB','DXB','Emirates'),
('DUB','CDG','Ryanair'),
('DUB','AMS','Ryanair'),
('DUB','IST','Ryanair'),
('MSP','ORD','Delta Airlines'),
('MSP','DFW','Delta Airlines'),
('MSP','LAX','SkyWest'),
('MSP','JFK','Delta Airlines'),
('MSP','LHR','Delta Airlines'),
('RUH','JED','Saudia'),
('RUH','DXB','Saudia'),
('RUH','CAI','Saudia'),
('RUH','LHR','Saudia'),
('RUH','AUH','Etihad Airways'),
('FLL','ATL','JetBlue'),
('FLL','EWR','JetBlue'),
('FLL','BWI','Southwest'),
('FLL','BOG','Delta Airlines'),
('FLL','YYZ','JetBlue'),
('MEL','SYD','Qantas'),
('MEL','HKG','Cathay Pacific'),
('MEL','DXB','Virgin Airlines'),
('MEL','SIN','Virgin Airlines'),
('MEL','KUL','Virgin Airlines'),
('CGK','HKG','Cathay Pacific'),
('CGK','KUL','AirAsia'),
('CGK','SIN','Singapore Airlines'),
('CGK','DXB','AirAsia'),
('CGK','MNL','Singapore Airlines'),
('LIS','MAD','Ryanair'),
('LIS','BCN','Ryanair'),
('LIS','AMS','Ryanair'),
('LIS','ORY','Ryanair'),
('LIS','DXB','Emirates'),
('LGA','JFK','Republic Airways'),
('LGA','LHR','Delta Airlines'),
('LGA','ORD','American Airlines'),
('LGA','ATL','Republic Airways'),
('LGA','YYZ','American Airlines'),
('PMI','MAD','Ryanair'),
('PMI','BCN','easyJet'),
('PMI','EWR','United'),
('PMI','FRA','Vueling Airlines'),
('PMI','MAN','Ryanair'),
('ORY','BCN','Vueling Airlines'),
('ORY','MAD','Vueling Airlines'),
('ORY','PMI','Ryanair'),
('ORY','LIS','Ryanair'),
('ORY','FCO','ITA Airways'),
('DTW','AMS','Delta Airlines'),
('DTW','ORD','United'),
('DTW','ATL','Delta Airlines'),
('DTW','MCO','Delta Airlines'),
('DTW','CLT','SkyWest'),
('HAN','AMS','Vietnam Airlines'),
('HAN','ICN','Vietnam Airlines'),
('HAN','MXP','ITA Airways'),
('HAN','SGN','Vietnam Airlines'),
('HAN','HKG','Cathay Pacific'),
('MAN','AMS','easyJet'),
('MAN','PMI','Ryanair'),
('MAN','BCN','Ryanair'),
('MAN','DOH','Qatar Airways'),
('MAN','JFK','Virgin Airlines'),
('ATH','MAD','Aegean Airlines'),
('ATH','AMS','Aegean Airlines'),
('ATH','BCN','Ryanair'),
('ATH','FRA','Aegean Airlines'),
('ATH','IST','Turkish Airlines'),
('VIE','AMS','Wizz Air Malta'),
('VIE','BCN','Ryanair'),
('VIE','PMI','Ryanair'),
('VIE','FRA','Wizz Air Malta'),
('VIE','MAD','Ryanair'),
('ZRH','DXB','Emirates'),
('ZRH','HKG','Cathay Pacific'),
('ZRH','AMS','easyJet'),
('ZRH','FRA','easyJet'),
('ZRH','BCN','easyJet'),
('PHL','ATL','American Airlines'),
('PHL','BOS','American Airlines'),
('PHL','MCO','Republic Airways'),
('PHL','ORD','PSA Airlines'),
('PHL','LHR','American Airlines'),
('NKG','CAN','China Eastern Airlines'),
('NKG','PEK','China Eastern Airlines'),
('NKG','CKG','China Eastern Airlines'),
('NKG','SZX','China Southern Airlines'),
('NKG','LAX','Air China'),
('KIX','HKG','Cathay Pacific'),
('KIX','ICN','Korean Air'),
('KIX','PVG','Air China'),
('KIX','TPE','Japan Airlines'),
('KIX','NRT','Japan Airlines'),
('CUN','MEX','AeroMéxico'),
('CUN','MAD','AeroMéxico'),
('CUN','YYZ','Air Canada'),
('CUN','BOG','Avianca'),
('CUN','MIA','Delta Airlines'),
('CSX','PKX','China Eastern Airlines'),
('CSX','XIY','China Eastern Airlines'),
('CSX','PEK','China Eastern Airlines'),
('CSX','TFU','China Southern Airlines'),
('CSX','HGH','China Southern Airlines'),
('DMK','KUL','AirAsia'),
('DMK','CGK','AirAsia'),
('DMK','NRT','Japan Airlines'),
('DMK','DXB','Emirates'),
('DMK','HKG','Cathay Pacific'),
('WUH','KMG','China Eastern Airlines'),
('WUH','SZX','China Southern Airlines'),
('WUH','TFU','China Southern Airlines'),
('WUH','CAN','China Southern Airlines'),
('WUH','PVG','China Southern Airlines'),
('CPH','AMS','KLM Royal Dutch Airlines'),
('CPH','BCN','Ryanair'),
('CPH','PMI','Scandinavian Airlines System'),
('CPH','CDG','Scandinavian Airlines System'),
('CPH','LHR','Scandinavian Airlines System'),
('STN','PMI','Ryanair'),
('STN','BCN','Ryanair'),
('STN','MAD','Ryanair'),
('STN','DUB','Ryanair'),
('STN','ATH','Ryanair'),
('CJU','ICN','Korean Air'),
('CJU','HKG','Cathay Pacific'),
('CJU','NRT','Japan Airlines'),
('CJU','PVG','Korean Air'),
('CJU','KIX','Korean Air'),
('HYD','BLR','IndiGO'),
('HYD','DXB','Emirates'),
('HYD','BOM','IndiGO'),
('HYD','LHR','Air India'),
('HYD','MUC','Lufthansa'),
('AUH','DXB','Etihad Airways'),
('AUH','JED','Etihad Airways'),
('AUH','IST','Turkish Airlines'),
('AUH','AMS','KLM Royal Dutch Airlines'),
('AUH','LHR','Etihad Airways'),
('CAI','RUH','Saudia'),
('CAI','JED','Saudia'),
('CAI','DXB','Saudia'),
('CAI','IST','Turkish Airlines'),
('CAI','AMS','KLM Royal Dutch Airlines'),
('CGO','SZX','China Southern Airlines'),
('CGO','SHA','China Eastern Airlines'),
('CGO','CAN','China Southern Airlines'),
('CGO','HGH','China Southern Airlines'),
('CGO','KMG','China Southern Airlines'),
('MXP','FCO','ITA Airways'),
('MXP','PVG','ITA Airways'),
('MXP','JFK','ITA Airways'),
('MXP','MAD','Wizz Air Malta'),
('MXP','HND','ITA Airways'),
('SLC','LAX','SkyWest'),
('SLC','DFW','Delta Airlines'),
('SLC','DEN','Delta Airlines'),
('SLC','PHX','Southwest'),
('SLC','LAS','SkyWest'),
('XMN','SHA','China Southern Airlines'),
('XMN','PEK','China Eastern Airlines'),
('XMN','CKG','China Southern Airlines'),
('XMN','URC','China Eastern Airlines'),
('XMN','TFU','China Southern Airlines'),
('IAD','AMS','KLM Royal Dutch Airlines'),
('IAD','ATL','United'),
('IAD','EWR','United'),
('IAD','DEN','United'),
('IAD','LHR','British Airways'),
('BWI','ATL','United'),
('BWI','MCO','United'),
('BWI','BOS','United'),
('BWI','ORD','Southwest'),
('BWI','LAX','Southwest'),
('FUK','HKG','Japan Airlines'),
('FUK','HND','Japan Airlines'),
('FUK','KIX','Japan Airlines'),
('FUK','ICN','Korean Air'),
('FUK','JFK','Japan Airlines'),
('URC','HKG','Cathay Pacific'),
('URC','KUL','AirAsia'),
('URC','PEK','China Eastern Airlines'),
('URC','PVG','China Southern Airlines'),
('URC','CAN','China Southern Airlines'),
('DCA','ATL','American Airlines'),
('DCA','JFK','American Airlines'),
('DCA','MIA','PSA Airlines'),
('DCA','ORD','PSA Airlines'),
('DCA','LHR','British Airways'),
('TAO','PVG','China Eastern Airlines'),
('TAO','SHA','China Eastern Airlines'),
('TAO','CAN','China Southern Airlines'),
('TAO','HGH','China Southern Airlines'),
('TAO','KMG','China Southern Airlines');

INSERT INTO VOLO(rotta, modello_aereo, timestamp)
VALUES
(4, 'A321', '2026-08-09 15:25'),
(6, 'A320', '2026-08-09 21:35'),
(12,'A388', '2026-08-08 19:40'),
(17,'A350', '2026-08-10 19:30'),
(23,'A320neo', '2026-08-10 6:30'),
(27,'B777-200', '2026-08-07 17:40'),
(31,'A330', '2026-08-08 15:00'),
(38,'A321', '2026-10-8 5:05'),
(42,'A321neo', '2026-08-09 13:00'),
(47,'A321neo', '2026-08-08 22:05'),
(53,'A321', '2026-08-10 12:05'),
(60,'B789', '2026-08-08 11:30'),
(62,'A350-900', '2026-08-09 20:30'),
(67,'A320', '2026-08-09 21:00'),
(71,'A350-900', '2026-08-10 12:45'),
(78,'B777-300', '2026-08-08 12:05'),
(85,'A321', '2026-08-09 7:20'),
(87,'B737-800', '2026-08-07 20:10'),
(91,'A321', '2026-08-08 11:00'),
(96,'A321', '2026-08-09 19:10'),
(102,'A321', '2026-08-09 17:30'),
(107,'A330', '2026-08-09 8:00'),
(114,'B777-200', '2026-08-10 15:40'),
(118,'B737', '2026-08-08 12:50'),
(123,'A320', '2026-08-09 17:00'),
(128,'B737M', '2026-08-09 14:45'),
(131,'A320', '2026-08-10 14:00'),
(137,'A321', '2026-08-11 21:10'),
(142,'B738', '2026-08-08 5:55'),
(149,'A359', '2026-08-09 1:40'),
(154,'B777-300', '2026-08-09 9:10'),
(159,'B737-900', '2026-08-11 8:00'),
(164,'A380', '2026-08-09 8:00'),
(170,'B737-800', '2026-08-10 21:00'),
(174,'A350-900', '2026-08-09 20:10'),
(178,'A350-900', '2026-08-10 14:00'),
(183,'A321', '2026-08-11 17:00'),
(187,'A321', '2026-08-08 21:15'),
(195,'B777-300', '2026-08-08 23:50'),
(197,'A330', '2026-08-08 17:30'),
(203,'B737-900', '2026-08-11 16:00'),
(208,'A321', '2026-08-09 16:50'),
(214,'B767-300', '2026-08-09 16:25'),
(218,'B737-800', '2026-08-09 7:00'),
(221,'A330', '2026-08-09 7:55'),
(227,'B737-800', '2026-08-09 20:00'),
(234,'B737-800', '2026-08-09 16:00'),
(238,'CRJ900', '2026-08-09 12:15'),
(242,'B787-800', '2026-08-08 20:35'),
(248,'B737M', '2026-08-09 8:40'),
(255,'A330', '2026-08-08 20:25'),
(259,'A320', '2026-08-07 14:35'),
(264,'A320', '2026-08-10 8:15'),
(269,'B777-300', '2026-08-10 22:20'),
(275,'B787-8', '2026-08-09 13:45'),
(280,'B767-400', '2026-08-09 10:25'),
(282,'A320neo', '2026-08-09 9:10'),
(286,'B737-800', '2026-08-09 12:00'),
(292,'A321', '2026-08-09 9:10'),
(297,'A330', '2026-08-09 9:20'),
(303,'A321neo', '2026-08-09 11:45'),
(307,'B777-300', '2026-08-09 14:10'),
(312,'B737-800', '2026-08-10 11:55'),
(318,'A320', '2026-08-09 4:45'),
(323,'B737', '2026-08-10 15:40'),
(330,'A330', '2026-08-10 6:15'),
(335,'A321', '2026-08-10 0:55'),
(339,'B737-800', '2026-08-10 6:30'),
(341,'B737-800', '2026-08-04 19:00'),
(348,'A321neo', '2026-08-09 20:15'),
(353,'A320', '2026-08-10 18:30'),
(358,'A321', '2026-08-10 9:25'),
(365,'B777-300', '2026-08-10 19:10'),
(367,'A320', '2026-08-10 10:55'),
(374,'A330', '2026-08-09 15:55'),
(380,'A320', '2026-08-08 9:50'),
(381,'B777-300', '2026-08-09 22:00'),
(387,'E175LR', '2026-08-10 18:35'),
(393,'B737-800', '2026-08-10 7:30'),
(397,'B787-10', '2026-08-10 12:35'),
(405,'A321', '2026-08-10 19:20'),
(411,'A320', '2026-08-09 19:50'),
(418,'B737-800', '2026-08-10 10:30'),
(424,'A320neo', '2026-08-10 8:25'),
(429,'B737-800', '2026-08-10 6:20'),
(433,'B737-900', '2026-08-10 12:55'),
(436,'A321neo', '2026-08-10 16:30'),
(442,'A321neo', '2026-08-12 21:25'),
(447,'A320', '2026-08-10 14:10'),
(453,'B737-800', '2026-08-09 22:25'),
(457,'A350-900', '2026-08-11 13:55'),
(465,'A321neo', '2026-08-11 22:05'),
(469,'B737-800', '2026-08-09 17:25'),
(475,'B777-300', '2026-08-10 21:05'),
(480,'B737-800', '2026-08-12 7:00'),
(484,'B787-900', '2026-08-10 14:50'),
(488,'B777-300', '2026-08-10 10:40'),
(492,'E175LR', '2026-08-10 18:23'),
(499,'A320neo', '2026-08-10 7:30');
