DROP DATABASE IF EXISTS DBVOLI_s;
CREATE DATABASE DBVOLI_s;
USE DBVOLI_s;

---------------------------
-- TABELLA AEROPORTI
---------------------------
CREATE TABLE AEROPORTO(
 iata VARCHAR(3) PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 continente VARCHAR(50) NOT NULL,
 stato VARCHAR(80) NOT NULL,
 citta VARCHAR(80) NOT NULL,
 passeggeri DECIMAL(5,1) NOT NULL,
 corsie INT NOT NULL
);

---------------------------
-- TABELLA COMPAGNIE AEREE
---------------------------
CREATE TABLE COMPAGNIA(
    nome VARCHAR(100) PRIMARY KEY,
    main_hub VARCHAR(3) NOT NULL,
    CONSTRAINT fk_hub_compagnia 
		FOREIGN KEY (main_hub)
        REFERENCES AEROPORTO(iata)
);

---------------------------
-- DB ROTTE
---------------------------
 CREATE TABLE ROTTA(
	id INT AUTO_INCREMENT PRIMARY KEY,
    iata_partenza VARCHAR(3) NOT NULL,
    iata_arrivo VARCHAR(3) NOT NULL,
    compagnia VARCHAR(30) NOT NULL,
    CONSTRAINT fk_partenza
		FOREIGN KEY (iata_partenza)
        REFERENCES AEROPORTO(iata),
	CONSTRAINT fk_arrivo
		FOREIGN KEY (iata_arrivo)
        REFERENCES AEROPORTO(iata),
	CONSTRAINT fk_compagnia
		FOREIGN KEY (compagnia)
        REFERENCES COMPAGNIA(nome)
);

---------------------------
-- DB VOLI
---------------------------
CREATE TABLE VOLO(
	id INT AUTO_INCREMENT PRIMARY KEY,
    rotta INT NOT NULL,
    modello_aereo VARCHAR(30) NOT NULL,
    timestamp DATETIME NOT NULL,
    
    CONSTRAINT fk_rotta
		FOREIGN KEY (rotta)
        REFERENCES ROTTA(id)
);

-------------------------
-- INSERIMENTO AEROPORTI
-------------------------
INSERT INTO AEROPORTO(iata, nome, continente, stato, citta, passeggeri, corsie)
VALUES
('ATL', 'Hartsfield Jackson Atlanta International Airport', 'NA', 'Stati Uniti', 'Atlanta', 108.1, 5),
('DXB', 'Dubai International Airport', 'AS', 'Emirati Arabi Uniti', 'Dubai', 92.3, 2),
('DFW', 'Dallas Fort Worth International Airport', 'NA', 'Stati Uniti', 'Dallas', 87.8, 7),
('HND', 'Tokyo Haneda International Airport', 'AS', 'Giappone', 'Tokyo', 85, 4),
('LHR','London Heathrow Airport','EU','Regno Unito','Londra', 83.9, 2),
('DEN','Denver International Airport','NA','Stati Uniti','Denver', 82.4, 6),
('IST','İstanbul Airport','EU','Turchia','Istanbul', 80.1, 5),
('ORD','Chicago O Hare International Airport','NA','Stati Uniti','Chicago', 80, 8),
('DEL','Indira Gandhi International Airport','AS','India','Nuova Delhi', 77.8, 4),
('PVG','Shanghai Pudong International Airport','AS','Cina','Shanghai', 76.8, 5),
('LAX','Los Angeles International Airport','NA','Stati Uniti','Los Angeles', 76.6, 4),
('CAN','Guangzhou Baiyun International Airport','AS','Cina','Guangzhou', 76.4, 5),
('ICN','Incheon International Airport','AS','Corea del Sud','Seoul', 71.2, 4),
('CDG','Charles de Gaulle International Airport','EU','Francia','Parigi', 70.3, 4),
('SIN','Singapore Changi Airport','AS','Singapore','Singapore', 67.7, 2),
('PEK','Beijing Capital International Airport','AS','Cina','Beijing', 67.4, 3),
('AMS','Amsterdam Airport Schiphol','EU','Paesi Bassi','Amsterdam', 66.8, 6),
('MAD','Adolfo Suárez Madrid–Barajas Airport','EU','Spagna','Madrid', 66.2, 4),
('JFK','John F Kennedy International Airport','NA','Stati Uniti','New York', 63.3, 4),
('BKK','Suvarnabhumi Airport','AS','Thailandia','Bangkok', 62.2, 3),
('FRA','Frankfurt Airport','EU','Germania','Francoforte', 61.6, 4),
('SZX','Shenzhen Bao an International Airport','AS','Cina','Shenzhen', 61.5, 3),
('CLT','Charlotte Douglas International Airport','NA','Stati Uniti','Charlotte', 58.8, 3),
('LAS','Harry Reid International Airport','NA','Stati Uniti','Las Vegas', 58.4, 4),
('MCO','Orlando International Airport','NA','Stati Uniti','Orlando', 57.2, 4),
('KUL','Kuala Lumpur International Airport','AS','Malesia','Kuala Lumpur', 57.1, 3),
('MIA','Miami International Airport','NA','Stati Uniti','Miami', 56, 4),
('BOM','Chhatrapati Shivaji International Airport','AS','India','Mumbai', 55.1, 2),
('BCN','Josep Tarradellas Barcelona-El Prat Airport','EU','Spagna','Barcellona', 55, 3),
('TFU','Chengdu Tianfu International Airport','AS','Cina','Chengdu', 54.9, 3),
('HKG','Hong Kong International Airport','AS','Hong Kong','Hong Kong', 53.1, 3),
('SEA','Seattle-Tacoma International Airport','NA','Stati Uniti','Seattle', 52.6, 3),
('DOH','Hamad International Airport','AS','Qatar','Doha', 52.5, 2),
('PHX','Phoenix Sky Harbor International Airport','NA','Stati Uniti','Phoenix', 52.3, 3),
('SFO','San Francisco International Airport','NA','Stati Uniti','San Francisco', 52.3, 4),
('MNL','Ninoy Aquino International Airport','AS','Filippine','Manila', 50.1, 2),
('PKX','Beijing Daxing International Airport','AS','Cina','Beijing', 49.4, 4),
('FCO','Rome-Fiumicino Leonardo Da Vinci Airport','EU','Italia','Roma', 49.2, 3),
('TPE','Taiwan Taoyuan International Airport','AS','Taiwan','Taipei', 49.1, 2),
('JED','King Abdulaziz International Airport','AS','Arabia Saudita','Jeddah', 48.9, 3),
('EWR','Newark Liberty International Airport','NA','Stati Uniti','Newark', 48.7, 3),
('CKG','Chongqing Jiangbei International Airport','AS','Cina','Chongqing', 48.5, 4),
('IAH','George Bush Intercontinental Houston Airport','NA','Stati Uniti','Houston', 48.1, 5),
('HGH','Hangzhou Xiaoshan International Airport','AS','Cina','Hangzhou', 48.1, 2),
('SHA','Shanghai Hongqiao International Airport','AS','Cina','Shanghai', 48, 2),
('KMG','Kunming Changshui International Airport','AS','Cina','Kunming', 47, 2),
('XIY','Xi an Xianyang International Airport','AS','Cina','Xianyang', 47, 4),
('YYZ','Toronto Lester B. Pearson International Airport','NA','Canada','Toronto', 46.8, 5),
('BOG','El Dorado International Airport','SA','Colombia','Bogota', 45.8, 2),
('MEX','Benito Juarez International Airport','NA','Messico','Città del Messico', 45.4, 2);


-------------------------
-- INSERIMENTO COMPAGNIA
-------------------------
INSERT INTO COMPAGNIA(nome, main_hub)
VALUES
('Ryanair', 'BCN'),
('KLM Royal Dutch Airlines','AMS'),
('Vueling Airlines','BCN'),
('easyJet','LHR'),
('SkyWest','DEN'),
('Southwest','PHX'),
('Delta Airlines','ATL'),
('Iberia','MAD'),
('American Airlines','DFW'),
('United','EWR'),
('Turkish Airlines','IST'),
('indiGO','BOM'),
('Air India', 'DEL'),
('China Eastern Airlines','PVG'),
('Lufthansa','FRA'),
('Qatar Airways','DOH'),
('British Airways','LHR'),
('China Southern Airlines','CAN'),
('Wizz Air Malta','FRA'),
('Air China','PEK'),
('Emirates','DXB'),
('Singapore Airlines','SIN'),
('Air France','CDG'),
('PSA Airlines','CLT'),
('Avianca','BOG'),
('ITA Airways','FCO'),
('Japan Airlines','HND'),
('Cathay Pacific','HKG'),
('Korean Air', 'ICN');

-------------------------
-- INSERIMENTO ROTTE
-------------------------
INSERT INTO ROTTA(iata_partenza, iata_arrivo, compagnia)
VALUES
('ATL','AMS','KLM Royal Dutch Airlines'),
('ATL','BCN','Delta Airlines'),
('ATL','IAH','Delta Airlines'),
('ATL','LAX','American Airlines'), 
('ATL','JFK','United'),
('DXB','HND','Qatar Airways'), 
('DXB','FRA','Emirates'),
('DXB','DEL','Air India'),
('DXB','HKG','Emirates'),
('DXB','SFO','Emirates'),
('DFW','PVG','American Airlines'),	
('DFW','LHR','British Airways'),
('DFW','DOH','Qatar Airways'),
('DFW','MIA','Delta Airlines'),
('DFW','ORD','United'),
('HND','SIN','Cathay Pacific'),
('HND','JFK','Japan Airlines'),
('HND','FCO','ITA Airways'),
('HND','DXB','Emirates'),
('HND','PEK','Japan Airlines'),
('LHR','AMS','KLM Royal Dutch Airlines'),
('LHR','CDG', 'Air France'),
('LHR','FRA','Lufthansa'),
('LHR','TFU','Air China'),
('LHR','LAX','British Airways'),
('DEN','LAS','United'),
('DEN','CDG','Air France'),
('DEN','PHX','American Airlines'),
('DEN','IAH','Southwest'),
('DEN','SEA','SkyWest'),
('IST','BCN','Turkish Airlines'),
('IST','DEL','Turkish Airlines'),
('IST','FRA','Lufthansa'),
('IST','CAN','China Southern Airlines'),
('IST','MIA','Turkish Airlines'),
('ORD','EWR','United'),
('ORD','ATL','American Airlines'),
('ORD','CLT','American Airlines'),
('ORD','SZX','Air China'),
('ORD','LHR','British Airways'),
('DEL','DXB','Air India'),
('DEL','BOM','IndiGO'),
('DEL','HKG','Cathay Pacific'),
('DEL','BKK','Air India'),
('DEL','JFK','Air India'),
('PVG','HND','China Eastern Airlines'),
('PVG','CAN','China Southern Airlines'),
('PVG','DOH','Emirates'),
('PVG','FCO','China Eastern Airlines'),
('PVG','LAX','Air China'),
('LAX','DFW','United'),
('LAX','SEA','Delta Airlines'),
('LAX','ATL','American Airlines'),
('LAX','SZX','Air China'),
('LAX','MAD','Iberia'),
('CAN','PKX','China Southern Airlines'),
('CAN','SHA','China Southern Airlines'),
('CAN','LHR','Air China'),
('CAN','SFO','China Southern Airlines'),
('CAN','FRA','China Southern Airlines'),
('ICN','HKG','Cathay Pacific'),
('ICN','HND','Korean Air'),
('ICN','JFK','Korean Air'),
('ICN','AMS','KLM Royal Dutch Airlines'),
('ICN','LAX','Korean Air'),
('CDG','BCN','Iberia'),
('CDG','FRA','Lufthansa'),
('CDG','LHR','British Airways'), 
('CDG','DXB','Emirates'),
('CDG','JFK','Air France'),
('SIN','HKG','Cathay Pacific'),
('SIN','HND','Singapore Airlines'),
('SIN','BKK','Singapore Airlines'),
('SIN','AMS','KLM Royal Dutch Airlines'),
('SIN','LAX','American Airlines'),
('PEK','HND','Air China'),
('PEK','CDG','Air France'),
('PEK','SFO','Air China'),
('PEK','SHA','Air China'),
('PEK','LHR','British Airways'),
('AMS','BCN','Vueling Airlines'),
('AMS','FRA','KLM Royal Dutch Airlines'),
('AMS','JFK','KLM Royal Dutch Airlines'),
('AMS','HKG','KLM Royal Dutch Airlines'),
('AMS','BOM','KLM Royal Dutch Airlines'),
('MAD','BCN','Iberia'),
('MAD','MEX','Ryanair'),
('MAD','BOG','Avianca'),
('MAD','JFK','Iberia'),
('MAD','IST','Turkish Airlines'),
('JFK','LAX','American Airlines'),
('JFK','MIA','American Airlines'),
('JFK','LHR','British Airways'),
('JFK','ATL','Delta Airlines'),
('JFK','HKG','Cathay Pacific'),
('BKK','SIN','Singapore Airlines'),
('BKK','TPE','Air China'),
('BKK','KUL','Singapore Airlines'),
('BKK','JED','Emirates'),
('BKK','ICN','Korean Air'),
('FRA','PVG','China Eastern Airlines'),
('FRA','IST','Lufthansa'),
('FRA','HND','Japan Airlines'),
('FRA','JFK','Air France'),
('FRA','AMS','KLM Royal Dutch Airlines'),
('SZX','PEK','China Eastern Airlines'),
('SZX','HGH','China Southern Airlines'),
('SZX','TFU','China Southern Airlines'),
('SZX','IST','Turkish Airlines'),
('SZX','LAX','Air China'),
('CLT','ATL','American Airlines'),
('CLT','MIA','PSA Airlines'),
('CLT','DFW','PSA Airlines'),
('CLT','MAD','American Airlines'),
('CLT','DEN','PSA Airlines'),
('LAS','LAX','Delta Airlines'),
('LAS','DEN','Southwest'),
('LAS','PHX','Southwest'),
('LAS','YYZ','SkyWest'),
('LAS','AMS','KLM Royal Dutch Airlines'),
('MCO','ATL','Southwest'),
('MCO','DFW','Southwest'),
('MCO','EWR','United'),
('MCO','LHR','British Airways'),
('MCO','DXB','Emirates'),
('KUL','SIN','Singapore Airlines'),
('KUL','HKG','Cathay Pacific'),
('KUL','CAN','China Southern Airlines'),
('KUL','LAX','Singapore Airlines'),
('KUL','IST','Turkish Airlines'),
('MIA','BOG','Avianca'),
('MIA','MAD','Iberia'),
('MIA','ATL','Delta Airlines'),
('MIA','DFW','Delta Airlines'),
('MIA','IAH','Southwest'),
('BOM','DOH','Emirates'),
('BOM','JED','IndiGO'),
('BOM','DEL','IndiGO'),
('BOM','DXB','Emirates'),
('BOM','PKX','Air India'),
('BCN','MAD','Iberia'),
('BCN','FRA','Ryanair'),
('BCN','FCO','easyJet'),
('BCN','CDG','Vueling Airlines'),
('BCN','JFK','Iberia'),
('TFU','CAN','China Eastern Airlines'),
('TFU','PVG','China Southern Airlines'),
('TFU','PEK','Air China'),
('TFU','FCO','Air China'),
('TFU','MAD','Air China'),
('HKG','TPE','Cathay Pacific'),
('HKG','HND','Air China'), 
('HKG','ICN','Korean Air'),
('HKG','SHA','Cathay Pacific'),
('HKG','LAX','Cathay Pacific'),
('SEA','DEN','American Airlines'),
('SEA','PHX','United'),
('SEA','LAX','Delta Airlines'),
('SEA','YYZ','SkyWest'),
('SEA','AMS','KLM Royal Dutch Airlines'),
('DOH','DXB','Qatar Airways'),
('DOH','BCN','Qatar Airways'),
('DOH','AMS','Qatar Airways'),
('DOH','LHR','Qatar Airways'),
('DOH','JFK','Qatar Airways'),
('PHX','LAX','Southwest'),
('PHX','DEN','Southwest'),
('PHX','DFW','SkyWest'),
('PHX','SEA','American Airlines'),
('PHX','ORD','American Airlines'),
('SFO','LAX','SkyWest'),
('SFO','LAS','United'),
('SFO','DEN','United'),
('SFO','CDG','Air France'),
('SFO','PEK','Delta Airlines'),
('MNL','HND','Cathay Pacific'),
('MNL','HKG','Cathay Pacific'),
('MNL','SIN','Singapore Airlines'),
('MNL','JFK','Singapore Airlines'),
('MNL','LHR','Singapore Airlines'),
('PKX','SZX','China Southern Airlines'),
('PKX','HKG','China Southern Airlines'),
('PKX','XIY','China Eastern Airlines'),
('PKX','IST','Turkish Airlines'),
('PKX','FRA','Air China'),
('FCO','MAD','Wizz Air Malta'),
('FCO','CDG','Wizz Air Malta'),
('FCO','PVG','ITA Airways'),
('FCO','JFK','ITA Airways'),
('FCO','BCN','Ryanair'),
('TPE','HKG','Air China'),
('TPE','BKK','Singapore Airlines'),
('TPE','HND','Japan Airlines'),
('TPE','SIN','Singapore Airlines'),
('TPE','LAX','Air China'),
('JED','DOH','Emirates'),
('JED','DEL','Qatar Airways'),
('JED','DXB','Qatar Airways'),
('JED','IST','Turkish Airlines'),
('JED','AMS','KLM Royal Dutch Airlines'),
('EWR','MAD','United'),
('EWR','ATL','United'),
('EWR','MCO','United'),
('EWR','IAH','Delta Airlines'),
('EWR','BCN','United'),
('CKG','SZX','China Southern Airlines'),
('CKG','HGH','China Eastern Airlines'),
('CKG','PVG','China Southern Airlines'),
('CKG','FCO','ITA Airways'),
('CKG','SIN','Singapore Airlines'),
('IAH','ORD','SkyWest'),
('IAH','ATL','United'),
('IAH','DFW','United'),
('IAH','AMS','United'),
('IAH','MEX','United'),
('HGH','SZX','Air China'),
('HGH','CAN','Air China'),
('HGH','PEK','China Southern Airlines'),
('HGH','KMG','China Southern Airlines'),
('HGH','FCO','ITA Airways'),
('SHA','SZX','China Eastern Airlines'),
('SHA','CAN','China Eastern Airlines'),
('SHA','XIY','China Eastern Airlines'),
('SHA','PEK','Air China'),
('SHA','CKG','China Eastern Airlines'),
('KMG','XIY','China Eastern Airlines'),
('KMG','SZX','China Southern Airlines'),
('KMG','CAN','China Southern Airlines'),
('KMG','KUL','Air China'),
('KMG','SHA','China Eastern Airlines'),
('XIY','KMG','China Eastern Airlines'),
('XIY','SZX','China Southern Airlines'),
('XIY','SHA','China Eastern Airlines'),
('XIY','CAN','China Southern Airlines'),
('XIY','FCO','ITA Airways'),
('YYZ','LHR','British Airways'),
('YYZ','AMS','KLM Royal Dutch Airlines'),
('YYZ','JFK','Delta Airlines'),
('YYZ','CDG','Air France'),
('YYZ','FRA','Lufthansa'),
('BOG','MAD','Avianca'),
('BOG','BCN','Avianca'),
('BOG','JFK','Avianca'),
('BOG','IST','Turkish Airlines'),
('BOG','AMS','KLM Royal Dutch Airlines'),
('MEX','MAD','Avianca'),
('MEX','BCN','Iberia'),
('MEX','JFK','Southwest'),
('MEX','IST','Turkish Airlines'),
('MEX','AMS','KLM Royal Dutch Airlines');

INSERT INTO VOLO(rotta, modello_aereo, timestamp)
VALUES
(4, 'A321', '2026-08-09 15:25'),
(6, 'A320', '2026-08-09 21:35'),
(12,'A388', '2026-08-08 19:40'),
(17,'A350', '2026-08-10 19:30'),
(23,'A320neo', '2026-08-10 6:30'),
(27,'B777-200', '2026-08-07 17:40'),
(31,'A330', '2026-08-08 15:00'),
(38,'A321', '2026-10-8 5:05'),
(42,'A321neo', '2026-08-09 13:00'),
(47,'A321neo', '2026-08-08 22:05'),
(53,'A321', '2026-08-10 12:05'),
(60,'B789', '2026-08-08 11:30'),
(62,'A350-900', '2026-08-09 20:30'),
(67,'A320', '2026-08-09 21:00'),
(71,'A350-900', '2026-08-10 12:45'),
(78,'B777-300', '2026-08-08 12:05'),
(85,'A321', '2026-08-09 7:20'),
(87,'B737-800', '2026-08-07 20:10'),
(91,'A321', '2026-08-08 11:00'),
(96,'A321', '2026-08-09 19:10'),
(102,'A321', '2026-08-09 17:30'),
(107,'A330', '2026-08-09 8:00'),
(114,'B777-200', '2026-08-10 15:40'),
(118,'B737', '2026-08-08 12:50'),
(123,'A320', '2026-08-09 17:00'),
(128,'B737M', '2026-08-09 14:45'),
(131,'A320', '2026-08-10 14:00'),
(137,'A321', '2026-08-11 21:10'),
(142,'B738', '2026-08-08 5:55'),
(149,'A359', '2026-08-09 1:40'),
(154,'B777-300', '2026-08-09 9:10'),
(159,'B737-900', '2026-08-11 8:00'),
(164,'A380', '2026-08-09 8:00'),
(170,'B737-800', '2026-08-10 21:00'),
(174,'A350-900', '2026-08-09 20:10'),
(178,'A350-900', '2026-08-10 14:00'),
(183,'A321', '2026-08-11 17:00'),
(187,'A321', '2026-08-08 21:15'),
(195,'B777-300', '2026-08-08 23:50'),
(197,'A330', '2026-08-08 17:30'),
(203,'B737-900', '2026-08-11 16:00'),
(208,'A321', '2026-08-09 16:50'),
(214,'B767-300', '2026-08-09 16:25'),
(218,'B737-800', '2026-08-09 7:00'),
(221,'A330', '2026-08-09 7:55'),
(227,'B737-800', '2026-08-09 20:00'),
(234,'B737-800', '2026-08-09 16:00'),
(238,'CRJ900', '2026-08-09 12:15'),
(242,'B787-800', '2026-08-08 20:35'),
(248,'B737M', '2026-08-09 8:40');
